### ISSUE TITLE
No touch callbacks after application. Loadlevel

### ISSUE THREAD

**Issue by jswigart** [TouchScript/TouchScript#136]
I'm registering callbacks with TouchManager. Instance. TouchesBegan, Touches ended, etc. 

After a call to Application. LoadLevel, these callbacks stop working. On latest code revisions as of today.

**Comment by valyard** [comment]
This was happening because TouchManagerInstance objects somehow got created and saved to scenes out of Play Mode. You can open a scene and search for "m_Name: TouchManager Instance". Not sure how they came through into scenes.

**Comment by pswl** [comment]
It is working as a charm now!
Thanks a lot!
