### ISSUE TITLE
windows store (windows phone 8.1 and universal) and old windows phone 8.0 build errors

### ISSUE THREAD

**Issue by asoft2013** [TouchScript/TouchScript#139]
Hi ,Valentin, while building solution in unity 4.6 f3 for windows store platform 
One Error on windows phone 8.0(old)
Error building Player: Exception: Error: method `System.Collections.Generic.List`1<!!0> System.Collections.Generic.List`1<TouchScript.TouchPoint>::ConvertAll<TouchScript.ITouch>(System.Converter`2<!0,!!0>)` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().

On Universal 8.1    i' ve got almost identical  16 errors. and on Phone 8.1 a have 8 similar errors (it’s windows store specific errors, with Android and IOS I have no problems)
1 Error
Reference Rewriter: Error: type `System.Converter`2` doesn't exist in target framework. It is referenced from TouchScript.dll at TouchScript.TouchManagerInstance.
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:726)
UnityEditor.HostView:OnGUI()
1. Error
   Reference Rewriter: Error: type `System.Converter`2` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
   UnityEngine.Debug:LogError(Object)
   PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
   PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
   PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:726)
   UnityEditor.HostView:OnGUI()
2. Error
   Reference Rewriter: Error: type `System.Converter`2` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().

UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:726)
UnityEditor.HostView:OnGUI()
4. Error
Reference Rewriter: Error: method `System.Void System.Converter`2<TouchScript.TouchPoint,TouchScript.ITouch>::.ctor(System.Object,System.IntPtr)`doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:726)
UnityEditor.HostView:OnGUI()
5. Error
Reference Rewriter: Error: type`System.Converter`2` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:726)
UnityEditor.HostView:OnGUI()
6. Error
Reference Rewriter: Error: type `System.Converter`2`doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:726)
UnityEditor.HostView:OnGUI()
7. Error
Reference Rewriter: Error: type`System.Converter`2` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:726)
UnityEditor.HostView:OnGUI()
8. Error
Reference Rewriter: Error: method `System.Collections.Generic.List`1<!!0> System.Collections.Generic.List`1<TouchScript.TouchPoint>::ConvertAll<TouchScript.ITouch>(System.Converter`2<!0,!!0>)`doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:726)
UnityEditor.HostView:OnGUI()
9. Error
Reference Rewriter: Error: type`System.Converter`2` doesn't exist in target framework. It is referenced from TouchScript.dll at TouchScript.TouchManagerInstance.
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:727)
UnityEditor.HostView:OnGUI()
10. Error
Reference Rewriter: Error: type `System.Converter`2` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().

UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:727)
UnityEditor.HostView:OnGUI()
11. Error
Reference Rewriter: Error: type `System.Converter`2`doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:727)
UnityEditor.HostView:OnGUI()
12. Error
Reference Rewriter: Error: method`System.Void System.Converter`2<TouchScript.TouchPoint,TouchScript.ITouch>::.ctor(System.Object,System.IntPtr)` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().

UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:727)
UnityEditor.HostView:OnGUI()
13. Error
Reference Rewriter: Error: type `System.Converter`2`doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:727)
UnityEditor.HostView:OnGUI()
14. Error
Reference Rewriter: Error: type`System.Converter`2` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:727)
UnityEditor.HostView:OnGUI()
15. Error
Reference Rewriter: Error: type `System.Converter`2`doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:727)
UnityEditor.HostView:OnGUI()
16. Error
Reference Rewriter: Error: method`System.Collections.Generic.List`1<!!0> System.Collections.Generic.List`1<TouchScript.TouchPoint>::ConvertAll<TouchScript.ITouch>(System.Converter`2<!0,!!0>)` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:727)
UnityEditor.HostView:OnGUI()
On Phone 8.1    i' ve got almost identical  8 errors.
1. Error
Reference Rewriter: Error: type `System.Converter`2`doesn't exist in target framework. It is referenced from TouchScript.dll at TouchScript.TouchManagerInstance.
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:740)
UnityEditor.HostView:OnGUI()
2. Error
Reference Rewriter: Error: type`System.Converter`2` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:740)
UnityEditor.HostView:OnGUI()
3. Error
Reference Rewriter: Error: type `System.Converter`2`doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:740)
UnityEditor.HostView:OnGUI()
4. Error
Reference Rewriter: Error: method`System.Void System.Converter`2<TouchScript.TouchPoint,TouchScript.ITouch>::.ctor(System.Object,System.IntPtr)` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:740)
UnityEditor.HostView:OnGUI()
5. Error
Reference Rewriter: Error: type `System.Converter`2`doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:740)
UnityEditor.HostView:OnGUI()
6. Error
Reference Rewriter: Error: type`System.Converter`2` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:740)
UnityEditor.HostView:OnGUI()
7. Error
Reference Rewriter: Error: type `System.Converter`2`doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:740)
UnityEditor.HostView:OnGUI()
8. Error
Reference Rewriter: Error: method`System.Collections.Generic.List`1<!!0> System.Collections.Generic.List`1<TouchScript.TouchPoint>::ConvertAll<TouchScript.ITouch>(System.Converter`2<!0,!!0>)` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:740)
UnityEditor.HostView:OnGUI()

**Comment by VSZM** [comment]
Hello. Can you include this in the next update please? I have just downloaded Touchscript and it still has this issue.

I admire your great work with the library though, thank you for it. If I will be able to monetize my game, I will remember to thank you for it.
