### ISSUE TITLE
Conversion from List of TouchPoint's to List of ITouch's fails

### ISSUE THREAD

**Issue by murderered** [TouchScript/TouchScript#141]
Trying to access the list of touches via events (TouchesBegin etc.) 

    foreach (ITouch CurrentTouch in EventArgs.Touches) {
        ...
    }

Does not work because:

    Reference Rewriter: Error: method `System.Collections.Generic.List`1<!!0> System.Collections.Generic.List`1<TouchScript.TouchPoint>::ConvertAll<TouchScript.ITouch>(System.Converter`2<!0,!!0>)` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.TouchManagerInstance::updateBegan().
    
    UnityEngine.Debug:LogError(Object)
    PostProcessMetroPlayer:RunReferenceRewriter(MetroSDK, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:489)
    PostProcessMetroPlayer:PostProcessSDKSpecific(MetroSDK, BuildTarget, BuildOptions, String, String, ProjectImages) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:1007)
    PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/BuildAgent/work/d63dfc6385190b60/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:740)
    UnityEditor.HostView:OnGUI()

How to correct this?

**Comment by valyard** [comment]
Windows Phone platform? I corrected this error in develop branch a while ago.

**Comment by murderered** [comment]
No, this happens when exporting to Windows Store (Desktop).

I know there was a similar error for Windows Phone, maybe it's only necessary to adapt the same solution for this bug.

Thanks.

**Comment by valyard** [comment]
The fix in question is here: https://github.com/TouchScript/TouchScript/commit/0aa7e54181c5b2d406ec9ae40b82e14604ee0ef8
I'll merge it into master soon and release the new version.

Original issue #139.
