### ISSUE TITLE
Building for Android requires Unity Android Pro

### ISSUE THREAD

**Issue by taleinat** [TouchScript/TouchScript#142]
I'm running automated Android builds of our apps on Windows. I'm getting the following build error:

```
Error building Player: SystemException: 'System.Net.Sockets' are supported only with Unity Android Pro. Referenced from assembly 'OSCsharp'.
```

OSCsharp appears to be part of the TouchScript plugin.

According to [this forum post](http://forum.unity3d.com/threads/systemexception-system-net-sockets-are-supported-only-with-unity-android-pro.153219/), this is caused by "using System;", which is indeed using in various places in the TouchScript code.

Your help would be appreciated!

**Comment by valyard** [comment]
This is because you use tuio input in your project. It uses oscsharp library and .net sockets. This assembly shouldn't be included in default touchscript package.

**Comment by taleinat** [comment]
Thanks!
