### ISSUE TITLE
ReleaseGesture when taking your finger off the button

### ISSUE THREAD

**Issue by famadori** [TouchScript/TouchScript#143]
Good day,

Is there any way to make the ReleaseGesture is triggered when a finger moves off the button and not when shooting the finger from the screen?
Example: When I press the button runs an animation and ReleaseGesture I Excuto another animation, however this animation is being performed only when I take your finger off the screen and not when shooting the finger button.
If I press the button and drag out of the ReleaseGesture button does not run, only when I take the finger from the screen.

Can you help me?
Thank U.

**Comment by valyard** [comment]
http://touchprefab.com/viewtopic.php?f=1&t=24259
