### ISSUE TITLE
Utils shouldn't be "Internal"; please expose TimedSequence to allow custom gestures

### ISSUE THREAD

**Issue by mikewoz** [TouchScript/TouchScript#144]
I'm trying to create my own gestures by extending the Gesture class, but I can't use some classes in the TouchScript/Utils namespace - specifically TimedSequence - because it is marked as "internal". TransformUtils are also marked as "internal" and could be handy.

I'm trying to make something similar to the "FlickGesture" and would like to use the TimedSequence class.

**Comment by valyard** [comment]
Well, this API is far from stable and some of it is considered ugly. I don't want you to use it and when I totally change it one day you'd complain (8 The code is there, you can copy it to your project with no responsibility from me whatsoever.
