### ISSUE TITLE
ArgumentException

### ISSUE THREAD

**Issue by asoft2013** [TouchScript/TouchScript#154]
Привет valyard ! В unity 4.6.3 f1. В 2D сцене имеются несколько объектов(клоны объекта А) с прикрепленным к ним Tap Gesture. Часть из этих объектов перекрыта 2D коллайдером другого объекта Б  и у всех жест Tap прекрасно работает. Проблема возникла в unity 5.0.0 f4 . При выполнении Tap жеста на объекте А, прикрытым 2D коллайдером другого объекта Б получаю ArgumentException в каждом кадре игры, моих скудных знаний не хватает решить эту проблему
изменив код в самом TouchScript, поэтому я назначил объект Б на новый Layer, а в Layer Mask у компонента CameraLayer2D убрал галочку с этого нового слоя . Проблемы больше нет, но Issue решил создать , вдруг окажется полезным. 

ArgumentException: An element with the same key already exists in the dictionary.
System.Collections.Generic.Dictionary`2[System.Int32,TouchScript.TouchPoint].Add (Int32 key, TouchScript.TouchPoint value) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:404)
TouchScript.TouchManagerInstance.updateBegan ()
TouchScript.TouchManagerInstance.updateTouches ()
TouchScript.TouchManagerInstance.Update ()

**Comment by valyard** [comment]
Попробуй с этим релизом, всё еще повторяется? https://github.com/TouchScript/TouchScript/releases/tag/6.5

**Comment by asoft2013** [comment]
пока перепроверял меня опередили ))) действительно появился новый Exception
 IndexOutOfRangeException: Array index is out of range.
TouchScript.Layers.CameraLayer2D.<sortHits>m__5 (RaycastHit2D a, RaycastHit2D b)

**Comment by valyard** [comment]
Вот этот?
https://github.com/TouchScript/TouchScript/issues/155
On CameraLayer2D in Inspector Tab there's a button "Update Sorting Layers". Can you press it and try again?

**Comment by asoft2013** [comment]
При нажатии на "Update Sorting Layers" получаю сразу (это даже до нажатия кнопки play): 
IndexOutOfRangeException: Array index is out of range.
TouchScript.Editor.Layers.CameraLayer2DEditor.getSortingLayerIdsToSortOrder ()
TouchScript.Editor.Layers.CameraLayer2DEditor.rebuildSortingLayers ()
TouchScript.Editor.Layers.CameraLayer2DEditor.OnInspectorGUI ()
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean forceDirty, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect, Boolean eyeDropperDirty) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1150)
UnityEditor.DockArea:OnGUI()

**Comment by valyard** [comment]
Please try this package: https://dl.dropboxusercontent.com/u/3601116/TouchScript_2dfix.unitypackage

**Comment by asoft2013** [comment]
Seems all works fine!!! valyard you are genius! big thanks!
