### ISSUE TITLE
windows store build errors

### ISSUE THREAD

**Issue by asoft2013** [TouchScript/TouchScript#157]
Hi, i' ve got an errors while build for windows store (universal app)
***
Reference Rewriter: Error: method `UnityEngine.Camera UnityEngine.Component::get_camera()` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.Behaviors.FullscreenTarget::Update().

UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(WSASDK, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:334)
PostProcessMetroPlayer:PostProcessSDKSpecific(WSASDK, BuildTarget, BuildOptions, String, String, ProjectImages, LibraryCollection) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:883)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:583)
UnityEditor.HostView:OnGUI()

***
Reference Rewriter: Error: method `UnityEngine.Collider UnityEngine.Component::get_collider()` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.Gestures.Simple.Transform2DGestureBase::OnEnable().

UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(WSASDK, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:334)
PostProcessMetroPlayer:PostProcessSDKSpecific(WSASDK, BuildTarget, BuildOptions, String, String, ProjectImages, LibraryCollection) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:883)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:583)
UnityEditor.HostView:OnGUI()

***

Reference Rewriter: Error: method `UnityEngine.Camera UnityEngine.Component::get_camera()` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Int32 TouchScript.Layers.CameraLayer2D::<sortHits>m__5(UnityEngine.RaycastHit2D,UnityEngine.RaycastHit2D).

UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(WSASDK, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:334)
PostProcessMetroPlayer:PostProcessSDKSpecific(WSASDK, BuildTarget, BuildOptions, String, String, ProjectImages, LibraryCollection) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:883)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:583)
UnityEditor.HostView:OnGUI()
***
Reference Rewriter: Error: method `UnityEngine.Camera UnityEngine.Component::get_camera()` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.Behaviors.FullscreenTarget::Update().

UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(WSASDK, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:334)
MetroPlugin:RunReferenceRewriter(String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/MetroPlugin.cs:148)
PostProcessMetroPlayer:PostProcessSDKSpecific(WSASDK, BuildTarget, BuildOptions, String, String, ProjectImages, LibraryCollection) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:890)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:583)
UnityEditor.HostView:OnGUI()
***

Reference Rewriter: Error: method `UnityEngine.Collider UnityEngine.Component::get_collider()` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.Gestures.Simple.Transform2DGestureBase::OnEnable().

UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(WSASDK, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:334)
MetroPlugin:RunReferenceRewriter(String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/MetroPlugin.cs:148)
PostProcessMetroPlayer:PostProcessSDKSpecific(WSASDK, BuildTarget, BuildOptions, String, String, ProjectImages, LibraryCollection) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:890)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:583)
UnityEditor.HostView:OnGUI()
*** 

Reference Rewriter: Error: method `UnityEngine.Camera UnityEngine.Component::get_camera()` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Int32 TouchScript.Layers.CameraLayer2D::<sortHits>m__5(UnityEngine.RaycastHit2D,UnityEngine.RaycastHit2D).

UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(WSASDK, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:334)
MetroPlugin:RunReferenceRewriter(String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/MetroPlugin.cs:148)
PostProcessMetroPlayer:PostProcessSDKSpecific(WSASDK, BuildTarget, BuildOptions, String, String, ProjectImages, LibraryCollection) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:890)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:583)
UnityEditor.HostView:OnGUI()
***

Reference Rewriter: Error: method `UnityEngine.Camera UnityEngine.Component::get_camera()` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.Behaviors.FullscreenTarget::Update().

UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(WSASDK, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:334)
PostProcessMetroPlayer:PostProcessSDKSpecific(WSASDK, BuildTarget, BuildOptions, String, String, ProjectImages, LibraryCollection) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:883)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:584)
UnityEditor.HostView:OnGUI()

***

Reference Rewriter: Error: method `UnityEngine.Collider UnityEngine.Component::get_collider()` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.Gestures.Simple.Transform2DGestureBase::OnEnable().

UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(WSASDK, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:334)
PostProcessMetroPlayer:PostProcessSDKSpecific(WSASDK, BuildTarget, BuildOptions, String, String, ProjectImages, LibraryCollection) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:883)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:584)
UnityEditor.HostView:OnGUI()
***

Reference Rewriter: Error: method `UnityEngine.Camera UnityEngine.Component::get_camera()` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Int32 TouchScript.Layers.CameraLayer2D::<sortHits>m__5(UnityEngine.RaycastHit2D,UnityEngine.RaycastHit2D).

UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(WSASDK, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:334)
PostProcessMetroPlayer:PostProcessSDKSpecific(WSASDK, BuildTarget, BuildOptions, String, String, ProjectImages, LibraryCollection) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:883)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:584)
UnityEditor.HostView:OnGUI()
***
Reference Rewriter: Error: method `UnityEngine.Camera UnityEngine.Component::get_camera()` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.Behaviors.FullscreenTarget::Update().

UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(WSASDK, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:334)
MetroPlugin:RunReferenceRewriter(String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/MetroPlugin.cs:148)
PostProcessMetroPlayer:PostProcessSDKSpecific(WSASDK, BuildTarget, BuildOptions, String, String, ProjectImages, LibraryCollection) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:890)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:584)
UnityEditor.HostView:OnGUI()
***

Reference Rewriter: Error: method `UnityEngine.Collider UnityEngine.Component::get_collider()` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Void TouchScript.Gestures.Simple.Transform2DGestureBase::OnEnable().

UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(WSASDK, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:334)
MetroPlugin:RunReferenceRewriter(String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/MetroPlugin.cs:148)
PostProcessMetroPlayer:PostProcessSDKSpecific(WSASDK, BuildTarget, BuildOptions, String, String, ProjectImages, LibraryCollection) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:890)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:584)
UnityEditor.HostView:OnGUI()

***

Reference Rewriter: Error: method `UnityEngine.Camera UnityEngine.Component::get_camera()` doesn't exist in target framework. It is referenced from TouchScript.dll at System.Int32 TouchScript.Layers.CameraLayer2D::<sortHits>m__5(UnityEngine.RaycastHit2D,UnityEngine.RaycastHit2D).

UnityEngine.Debug:LogError(Object)
PostProcessMetroPlayer:RunReferenceRewriter(WSASDK, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:334)
MetroPlugin:RunReferenceRewriter(String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/MetroPlugin.cs:148)
PostProcessMetroPlayer:PostProcessSDKSpecific(WSASDK, BuildTarget, BuildOptions, String, String, ProjectImages, LibraryCollection) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:890)
PostProcessMetroPlayer:PostProcess(BuildTarget, BuildOptions, String, String, String, String) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessMetroPlayer.cs:584)
UnityEditor.HostView:OnGUI()

**Comment by shreks7** [comment]
Check out this pull - https://github.com/TouchScript/TouchScript/pull/158. See if this works for you.

**Comment by asoft2013** [comment]
I' ve just create new empty scene in unity 5, then delete touchScript folder (all framework and examples) . Reimport TouchScript  6.4 and when unity asked me to update old APIs I'd click "...Go Ahead" . After that I extract touchscript exemples and see the same dialog asked me to update old APIs I'd click "...Go Ahead" . Then after two automatic updates, errors are gone ... miracle

**Comment by asoft2013** [comment]
thanks for the tip!

**Comment by shreks7** [comment]
Yes, if you create a new project in 5.0. It works. But if you wish to port an existing project from 4.6, you can use my fix. (Though you need to rebuild the .dlls for now, until the merge is accepted).

**Comment by valyard** [comment]
Please check if your issue still appears with the new release: https://github.com/TouchScript/TouchScript/releases/tag/6.5
