### ISSUE TITLE
Win7TouchInput works only with TouchDebugger question.

### ISSUE THREAD

**Issue by FlYnN91** [TouchScript/TouchScript#166]
Hi, 
Thank you for TouchScript. It seems a very powerfull and looked after tool. I am getting by hands into Unity 5 on Windows 7 and I have managed to make the TouchScript examples to work. Specifically, I am interested in getting all touches and processing them myself. I have imported the Win7TouchInput and it works with the Touch Debugger. I can see the blue circles (I followed the gestures tutorial) with Touch Debugger. I have added a separate C# script file attached it to the TouchScript GameObject as component and its Update function is this. The value is always 0, even though there are circles on the screen.

void Update () {
    Debug.Log (Input.touchCount);		
}

What am I doing wrong?

**Comment by FlYnN91** [comment]
I think I got it working. I found that I can reference from the TouchManager.Instance.ActiveTouches.Count. Is this a good way to about it? Thanks

**Comment by valyard** [comment]
Right, TouchScript doesn't rely on built-in Unity Input system much.
TouchManager.Instance.ActiveTouches contains currently present touches in the system.
