### ISSUE TITLE
Pinch to Zoom Gesture (ScaleGesture) with Unity UI

### ISSUE THREAD

**Issue by malitvin** [TouchScript/TouchScript#167]
I am putting a Scale Gesture Component on a Unity UI Image and have added <ScaleGesture>().Scaled += ScaleHanlder; events to it in order for it to have a pinch to zoom effect to scale the image. But the ScaleHanlder method is not getting called. I am wondering if there is some special way to get gestures to work with Unity UI objects?

**Comment by valyard** [comment]
Right now you have to have colliders on all objects you want to be interactable from TouchScript.
Add a collider to your UI object to make it work.
Also consult this thread on the forums: http://touchprefab.com/viewtopic.php?f=4&t=12
People created their wrappers to Unity UI.
