### ISSUE TITLE
Touch not working on multiple screens

### ISSUE THREAD

**Issue by mumtazmuttahir** [TouchScript/TouchScript#168]
I have 6 screens grid (row x column -> 2 x 3). I need use this grid as one screen. Since the touchscript plugin is being used on one screen so far, on spread the application on the grid, touches get registered on random locations on any of the random screens.

Any solutions?

**Comment by valyard** [comment]
I actually don't know. I have never had such setup.
What screens, PC, video card and OS are you using?

**Comment by mumtazmuttahir** [comment]
its multitaction iWall

All the 6 screens are connected to the switch and given the specific IP to each of them. The switch is then connected to NIC(the ethernet card). I am using 2 GeForce960 graphic cards for 3 screens each. OS is Windows 7.

**Comment by SawnOffSausage** [comment]
Hi, we are having the same issues.
We have 6 multitaction monitors set up to 2 Geforce GTX980s. The touch only seems to work for one monitor and won't spread out accross to the other 5.
We are using windows 7 also.

**Comment by valyard** [comment]
@SawnOffSausage can you ping me on email => v [аt] lent [dоt] in
