### ISSUE TITLE
Problem with uGUI Collider

### ISSUE THREAD

**Issue by rayfont** [TouchScript/TouchScript#169]
Hi
I'm using Unity5 and Touchscript
i made button with ugui and attach collider 
because i dont want touch ray pass through the button
but touch ray pass though the button and hit the 3D object
i tested 3dcoliider, 2dcollider but ray always pass through
what am i missing?

**Comment by valyard** [comment]
Do you have CameraLayer set up correctly?
Is your UI NOT in screen overlay mode?
