### ISSUE TITLE
2DLayer Sorting: Exception on overlapping 2DColliders with not spriterenderer attached

### ISSUE THREAD

**Issue by Podden** [TouchScript/TouchScript#175]
When 2 2DColliders overlapping and not spriterenderer is attached (ergo no spritesorting for touchscript possible) I get a "Already in the dictionary exception". Is this just a "Sorry your fault" problem or can this be fixed, perhaps by plain old "first comes first serve" sorting. 
You should at least print out a warning for this :).

**Comment by valyard** [comment]
What version are you using?
Can you provide a small example?

**Comment by Podden** [comment]
I'm using the 6.6 release in Unity 5.0.1f1. Small Example:
- Make a new scene
- Empty Gameobject with components: TouchManager, CameraLayer2D and an Input Module
- 2 Gameobjects with 2DBoxcollider which overlap and a Tapgesture component
- Click on the overlapping position, bäm Exceptions :)

**Comment by Podden** [comment]
Maybe this can help:

I get this Exceptions when I've attached the CameraLayer2D to a gameobject without a camera component.
When the CameraLayer2D is attached to the Camera gameobject, the touch just stops working without exceptions.

Here's the log of the first Exception in the row:

MissingComponentException: There is no 'Camera' attached to the "TouchManager" game object, but a script is trying to access it.
You probably need to add a Camera to the game object "TouchManager". Or your script needs to check if the component is attached before using it.
TouchScript.Layers.CameraLayer2D.<sortHits>m__5 (RaycastHit2D a, RaycastHit2D b)
System.Array.qsort[RaycastHit2D] (UnityEngine.RaycastHit2D[] array, Int32 low0, Int32 high0, System.Comparison`1 comparison) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Array.cs:1774)
System.Array.Sort[RaycastHit2D] (UnityEngine.RaycastHit2D[] array, Int32 length, System.Comparison`1 comparison) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Array.cs:1699)
Rethrow as InvalidOperationException: Comparison threw an exception.
System.Array.Sort[RaycastHit2D] (UnityEngine.RaycastHit2D[] array, Int32 length, System.Comparison`1 comparison) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/Array.cs:1702)
System.Collections.Generic.List`1[UnityEngine.RaycastHit2D].Sort (System.Comparison`1 comparison) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/List.cs:579)
TouchScript.Layers.CameraLayer2D.sortHits (UnityEngine.RaycastHit2D[] hits)
TouchScript.Layers.CameraLayer2D.castRay (Ray ray, ITouchHit& hit)
TouchScript.Layers.CameraLayerBase.Hit (Vector2 position, ITouchHit& hit)
TouchScript.Layers.TouchLayer.beginTouch (ITouch touch, ITouchHit& hit)
TouchScript.Layers.TouchLayer.BeginTouch (TouchScript.TouchPoint touch)
TouchScript.TouchManagerInstance.updateBegan ()
TouchScript.TouchManagerInstance.updateTouches ()
TouchScript.TouchManagerInstance.Update ()

**Comment by valyard** [comment]
Right, CameraLayer must be on the Camera.

But what's up with overlapping colliders? Can you provide an example?

**Comment by Podden** [comment]
oh my bad. Seems to be a follow up of the CameraLayer misplacement. You're calling Getcomponent<Camera> in CameraLayer2D only when more than one collider is touched so the exception obviously does only occur when I touch theo colliders at the same tome.
Sorry, everything fine here ;).
