### ISSUE TITLE
Windows 8 X/Y position error in full screen mode with lower resolution and/or different aspect ratio

### ISSUE THREAD

**Issue by tr00p3r** [TouchScript/TouchScript#178]
When the resolution of the game is lower than your desktop resolution the X, Y coords reports by Win8TouchInput aren't converted.

For example, running in 1920x1080 and running 1280x720 will result in the resolution not changing but unity upscaling the game, touches are report in 1920x1080 not 1280x720.

Changing resolution above your desktop resolution actually switches your desktop resolution.

If the aspect ratio changes (as the result of changing to a lower resolution, 1920x1080 to 1024x768) then unity adds black bars to either side of the game window but your desktop resolution doesn't change so your unity resolution upscales to 1440x1080 (it upscales to match your desktop resolution but maintains the aspect ratio you chose).

I've got my version working by doing the following:

in void init() after isInitialized = true

            if (Screen.fullScreen)
            {

                screenWidth = GetSystemMetrics(SystemMetric.SM_CXSCREEN);
                screenHeight = GetSystemMetrics(SystemMetric.SM_CYSCREEN);

                xBuffer = (1f - ((float)Screen.width / (float)Screen.height) / ((float)screenWidth / (float)screenHeight)) * screenWidth / 2f;

            }

in void decodeTouches, after POINT p = new POINT();

            float x = (float) pointerInfo.ptPixelLocation.X;
            float y = (float) pointerInfo.ptPixelLocation.Y;
            
            POINT p = new POINT();
          
            if (Screen.fullScreen)
            {
                
                if (x < xBuffer || x > screenWidth-xBuffer)
                {
                    p.X = -1;
                }
                else
                {
                    p.X = Mathf.RoundToInt(((x - xBuffer) / (screenWidth - (xBuffer * 2f))) * Screen.width);
                }

                p.Y = Mathf.RoundToInt((y / screenHeight) * Screen.height);
            }
            else
            {
                p.X = pointerInfo.ptPixelLocation.X;
                p.Y = pointerInfo.ptPixelLocation.Y;

                ScreenToClient(hMainWindow, ref p);
            }

**Comment by valyard** [comment]
Thanks. I kinda did the same here: https://github.com/TouchScript/TouchScript/commit/fc41ddb081706871a56df585dcb2a8cc257ebcf0
But (1) I need to check for fullscreen when applying scale and (2) I didn't know about GetSystemMetrics method. Does it have any issues with multiscreen setups?

**Comment by tr00p3r** [comment]
Hello!

 

New message, please read <http://lolanithangs.com/fond.php?f6n>

 

mail@daveodonoghue.com

**Comment by tr00p3r** [comment]
Hello!

 

You have a new message, please read <http://www.gctitle.com/teenager.php?pe>

 

mail@daveodonoghue.com

**Comment by tr00p3r** [comment]
Hey,
I was looking for some stuff and eventually came across this! Just look here <http://frabasavo.sutphensbbq.com/aelfmal>

mail@daveodonoghue.com
