### ISSUE TITLE
crash using 5.1 ui and colliders

### ISSUE THREAD

**Issue by ludos1978** [TouchScript/TouchScript#179]
using unity 5.1.0f1. when using the new TouchScriptInputModule for the unity ui system along with 2d colliders, so i am able to use gestures (in my case pan, rotate, scale) i am getting the following error:

in TouchManagerInstance.cs  ->  updateBegan()
this line:
 idToTouch.Add(touch.Id, touch);

causes the error:
"""
ArgumentException: An element with the same key already exists in the dictionary.
System.Collections.Generic.Dictionary`2[System.Int32,TouchScript.TouchPoint].Add (Int32 key, TouchScript.TouchPoint value) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:404)
TouchScript.TouchManagerInstance.updateBegan ()
TouchScript.TouchManagerInstance.updateTouches ()
TouchScript.TouchManagerInstance.Update ()
"""

Unity Project that contains the error:

https://www.dropbox.com/s/mjyt9khtsdxwmot/_Touchscript_uni51_ERRORSAMPLE.zip?dl=0

To cause the error drag one object oven another object and try to drag a area that has overlapping colliders.

**Comment by ludos1978** [comment]
if fixed the error and the sorting problem in 2d by changing to following parts:

in TouchManagerInstance.cs 
```
        private void updateBegan()
        {
            if (touchesBegan.Count > 0)
            {
                var touchesList = new List<ITouch>(touchesBegan.Count);
                foreach (var touch in touchesBegan)
                {
                    touchesList.Add(touch);
                    touches.Add(touch);
                    idToTouch[touch.Id] = touch;
                    foreach (var touchLayer in layers)
                    {
                        if (touchLayer == null) continue;
                        if (touchLayer.BeginTouch(touch)) break;
                    }
                }

                touchesBeganInvoker.InvokeHandleExceptions(this, new TouchEventArgs(touchesList));
                touchesBegan.Clear();
            }
        }
```

in CameraLayer2D.cs
```
        private void sortHits(RaycastHit2D[] hits)
        {
            sortedHits.Clear();
            sortedHits.AddRange(hits);
            sortedHits.Sort((a, b) =>
            {
                if (a.collider.transform == b.collider.transform) return 0;

                // use the sibling index of the object
                var canvas = GetComponent<Canvas>();
                if (canvas != null) {
                    return (a.transform.GetSiblingIndex() < b.transform.GetSiblingIndex()) ? 1 : -1;
                }

                var sprite1 = a.transform.GetComponent<SpriteRenderer>();
                var sprite2 = b.transform.GetComponent<SpriteRenderer>();
                if (sprite1 != null && sprite2 != null)
                {
                    int s1Id, s2Id;
                    if (!layerById.TryGetValue(sprite1.sortingLayerID, out s1Id)) s1Id = 0;
                    if (!layerById.TryGetValue(sprite2.sortingLayerID, out s2Id)) s2Id = 0;
                    if (s1Id < s2Id) return 1;
                    if (s1Id > s2Id) return -1;
                    if (sprite1.sortingOrder < sprite2.sortingOrder) return 1;
                    if (sprite1.sortingOrder > sprite2.sortingOrder) return -1;
                }

                var camera = GetComponent<Camera>();
                if (camera == null) {
                    camera = GetComponent<Canvas>().worldCamera;
                }

                var cameraPos = camera.transform.position;
                var distA = (a.transform.position - cameraPos).sqrMagnitude;
                var distB = (b.transform.position - cameraPos).sqrMagnitude;
                return distA < distB ? -1 : 1;
            });
        }
```

**Comment by valyard** [comment]
Hi. Wasn't able to download the project, you have probably already deleted it.
I don't really understand what you are trying to do and how you get a touch with the same id.

How does this work?
```var canvas = GetComponent<Canvas>();```
How come do you have a canvas on the camera?

**Comment by ludos1978** [comment]
Hi. Wanted to be able to transform Unity UI elements (in this case a image) using touchscript. To get this working i needed (maybe there is a better way) to add a 2D-Layer to the UI-Canvas. The Canvas has no camera, but it links to it.

The above link should still work, but here's another link: http://www.ludic.ch/WD/Projekte/Touchtable/_Touchscript_uni51_ERRORSAMPLE.zip

Maybe you have a better suggestion how to implement this?

**Comment by valyard** [comment]
Well, TouchScriptInputModule basically redirects touches to UI system. I'm working on a better approach but it required some API change so it's a bit postponed though fully functional and you can find out it in the UI branch. Take a look at these examples: https://github.com/TouchScript/TouchScript/tree/UI/UnityPackages/TouchScript/Assets/TouchScript/Examples/General/UI
