### ISSUE TITLE
Xcode Armv7s issue 

### ISSUE THREAD

**Issue by Kenna09** [TouchScript/TouchScript#183]
My app runs great with Arm64 but not with Armv7. I am panning an object on a X and Z axis and it work perfectly fine on an Arm64 iphone but on anything else the object will only pan up and down on the Z axis while it remains frozen on the X axis.
 I am using unity3d IL2CPP with architecture set to universal and the Xcode architecture set to both armv5 and arm64.  When I originally used the Mono2.0 with the Xcode it ran just fine with ARMv7 but then i found out that Apple doesnt allow Mono2.0 and requires ARM64.  So naturally I switched over and now I have this odd bug.  Thanks for your time.

**Comment by Kenna09** [comment]
Even when I tried it with the Button prefab that comes from the pan example scene, I get the same result.  The button only moves on the Z axis and not the X.

**Comment by valyard** [comment]
So, do I get it right, when you run Pan example on a 32bit device the cube moves only along Z axis?
The same scene works fine on a 64bit device, right? What devices are you using?

**Comment by Kenna09** [comment]
yes, you are right. 
On iPhones 5 and 4s it only pans on the Z axis but it works completely fine on iPhones 5s and 6. It worked on the 4s before I switched the mono2 to IL2CPP.  I made the game using unity3D.

**Comment by valyard** [comment]
I'm sorry I don't have a 32bit device. I tried to run a 32bit app on iPhone 6 and it worked fine o.O

**Comment by Kenna09** [comment]
Okay.  So is there anything I can do? Anything you could recommend or maybe someone else that could help?  Thanks for your time.

**Comment by valyard** [comment]
Have you tried building a 32bit app and running it on a 64bit device?

**Comment by Kenna09** [comment]
Well that is not an option because apple recently, within the last few months, now requires all apps to be 64bit.  So my only option is to use 64bit only or universal, which both do not function correctly with the 32bit Iphones.  I have zero problems on the android side of things. 
could it be a setting I am missing within Xcode? it has so many setting but i set both unity 3d and xcode for universal bit.

**Comment by valyard** [comment]
I mean try to run a 32bit-only build on a 64bit device to see if the problem persists.
Both versions run fine on my iphone 6.

Otherwise you will need to figure out what data is wrong. Check if you get correct coordinates from PanGesture first. You can subscribe to its Panned event with another script and Debug.Log(gesture.WorldDeltaPosition);

**Comment by Kenna09** [comment]
I fixed it.  I stripped my player to just using the simple pan gesture script and the transformer 2D script, the only two i needed to pan, and it worked with IL2CPP set to universal.  Panning runs smooth just like in all the other versions. Thanks

**Comment by Kenna09** [comment]
It must have been one of the other scripts or gestures from that Pan example that was causing it not to pan on the X axis. I did not pin point the issue but it has to be one of those.
