### ISSUE TITLE
How to cancel SimplePanGesture when touch pans out of the collider?

### ISSUE THREAD

**Issue by TiborUdvari** [TouchScript/TouchScript#185]
I am moving 2D Sprites exclusively horizontally, using `SimplePanGesture` to track the movement. 
I would like to cancel the `Gesture` if the active touches leave the box collider. 
So, basically if I'm moving a object left to right on a fixed y axis, I would like to stop my object translation if the user, while panning goes to pan up or down of the moved object.

**Comment by valyard** [comment]
Sorry, right now you can't cancel a gesture.
I'm working on it.
