### ISSUE TITLE
SimpleScaleGesture / ScaleGesture freezes gameobject when scaling to near 0.

### ISSUE THREAD

**Issue by superjaska** [TouchScript/TouchScript#189]
Made my own quickfix to transformer2d to line 87:
if (localScaleToGo.x < .1f) localScaleToGo = new Vector3(.1f, .1f, .1f); 

I think issue should be still deeper detected....

**Comment by valyard** [comment]
What do you mean by "freezes"?
Do you have an example?

**Comment by superjaska** [comment]
i can send you unitypackage or video? .. i dont know how this is usually done here...
by freezing i mean that touchscript and object it is controlling became unresponsive,

**Comment by valyard** [comment]
Send me a project if you can please.
You can do it by email: v [at] lent [dot] in
