### ISSUE TITLE
Planned Linux Support?

### ISSUE THREAD

**Issue by sapandiwakar** [TouchScript/TouchScript#193]
Do you plan to add linux support for TouchScript? We have a Displax Ultrafit touch skin which provides HID multitouch input to Ubuntu, but this input isn't passed on to Unity TouchScript as there are no compatible input sources yet. 

There is some information on how this can be achieved using by reading the device using `evtest` tool [here](http://stackoverflow.com/a/28845362/643109).

**Comment by valyard** [comment]
I personally don't since I don't have linux.
Isn't this what you were looking for? 
https://github.com/bretternst/TouchScript
