### ISSUE TITLE
Camera Perspective Editor

### ISSUE THREAD

**Issue by spotd** [TouchScript/TouchScript#194]
I am trying to use Touchscript alongside Camera Perspective Editor, as i want a specific pseudo 3d view

The developer of this asset has informed I can locate the standard point methods and replace with his to get it to work - 

Camera.ViewportPointToRay ---> CameraPerspectiveEditor.ViewportPointToRay
Camera.ScreenPointToRay ---> CameraPerspectiveEditor.ScreenPointToRay
Camera.WorldToScreenPoint---> CameraPerspectiveEditor.WorldToScreenPoint
Camera.WorldToViewportPoint---> CameraPerspectiveEditor.WorldToViewportPoint

Any pointers as to where these can be accessed?

**Comment by valyard** [comment]
Camera.ScreenPointToRay is used here: https://github.com/TouchScript/TouchScript/blob/master/TouchScript/Layers/CameraLayerBase.cs#L63
The best way would be to copy CameraLayerBase and CameraLayer into your own classes and change this line.

**Comment by spotd** [comment]
Ok got it working, but only after disabling the if statements. -

using UnityEngine;
using System.Collections;
using TouchScript.Layers;
using TouchScript.Hit;


public class CameraFix : CameraLayer {


	private CameraPerspectiveEditor CPE;
	
	public void Start ()
	{
		CPE = gameObject.GetComponent<CameraPerspectiveEditor> ();
	}

	public override LayerHitResult Hit(Vector2 position, out ITouchHit hit)
	{
	//	if (base.Hit(position, out hit) == LayerHitResult.Miss) return LayerHitResult.Miss;
	//	if (_camera == null) return LayerHitResult.Error;
	//	if (_camera.enabled == false || _camera.gameObject.activeInHierarchy == false) return LayerHitResult.Miss;
	//	if (!_camera.pixelRect.Contains(position)) return LayerHitResult.Miss;

		Ray ray = CPE.ScreenPointToRay(position);
		Debug.Log ("HIT " + ray.direction);
		return castRay(ray, out hit);
	}
}
