### ISSUE TITLE
Unity 5 - Windows 7 touch input causing the native touch not work

### ISSUE THREAD

**Issue by madhuatlink** [TouchScript/TouchScript#195]
I have a Unity Windows app which use Touch script library to recognize Windows 7 touches in 3D models. I have been working in Unity 4.3 up to now and everything has been working fine.

Now I want to upgrade to Unity 5. When I do that still the 3D model touches are working fine. But when I have the Windows 7 touch input enabled in Touch script, the rest of the app's single touches don't work anymore, e.g. HTML links/buttons (shown through coherent UI) or GUI button clicks etc..

With unity 4.3 I used Touchscript 5. I tried with that in Unity 5 and also with the latest 6.10 version. With both, if the Windows 7 touch is enabled, other touches are not working.

Today we tried by building from the Touchscript latest code and when debugging figured that in 
Win7TouchInput.cs  private void init() function if we comment the line oldWndProcPtr = SetWindowLongPtr(hMainWindow, -4, newWndProcPtr); then the normal touches work. But with this commented the Touch script funcionality is not working. (I really don't have much idea what that code does.)

Any help on how to get this fixed will be really appreciated.

**Comment by valyard** [comment]
Let's keep the conversation here: http://touchprefab.com/posting.php?mode=reply&f=1&t=24378
