### ISSUE TITLE
Errors in windows store build(phone 8.1, universal 8.1, universal 10)

### ISSUE THREAD

**Issue by asoft2013** [TouchScript/TouchScript#198]
Hi, Valintin, There are 168 errors in windows store universal 8.1
build. Here some of them:

Reference rewriter: Error: method `System.Int32 System.Net.Sockets.UdpClient::Send(System.Byte[],System.Int32)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPTransmitter::Send(OSCsharp.Data.OscPacket).
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/PostProcessWinRT.cs:581)
PostProcessUniversal81:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessUniversal81.cs:124)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/PostProcessWinRT.cs:123)
PostProcessUniversal81:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessUniversal81.cs:42)
UnityEditor.HostView:OnGUI()

Reference rewriter: Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPTransmitter::Send(OSCsharp.Data.OscPacket).
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/PostProcessWinRT.cs:581)
PostProcessUniversal81:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessUniversal81.cs:124)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/PostProcessWinRT.cs:123)
PostProcessUniversal81:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessUniversal81.cs:42)
UnityEditor.HostView:OnGUI()

Reference rewriter: Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPTransmitter::Send(OSCsharp.Data.OscPacket).
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/PostProcessWinRT.cs:581)
PostProcessUniversal81:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessUniversal81.cs:124)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/PostProcessWinRT.cs:123)
PostProcessUniversal81:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessUniversal81.cs:42)
UnityEditor.HostView:OnGUI()

Reference Rewriter found some errors while running with command --target="Temp\StagingArea\TouchScript7.Windows\OSCsharp.dll" --additionalreferences="Temp\StagingArea\TouchScript7.Windows" --platform="C:\Program Files (x86)\Windows Kits\8.1\References\CommonConfiguration\Neutral\Windows.winmd" --support="Temp\StagingArea\TouchScript7.Windows\WinRTLegacy.dll" --supportpartialns=Unity.Partial --system=System --dbg=pdb --framework="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5.1" --alt=System.Xml.Serialization --ignore=System.IConvertible,mscorlib.
Error: method `System.Collections.ObjectModel.ReadOnlyCollection`1<!0> System.Collections.Generic.List`1<OSCsharp.Data.OscBundle>::AsReadOnly()` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Collections.Generic.IList`1<OSCsharp.Data.OscBundle> OSCsharp.Data.OscBundle::get_Bundles().
Error: method `System.Collections.ObjectModel.ReadOnlyCollection`1<!0> System.Collections.Generic.List`1<OSCsharp.Data.OscMessage>::AsReadOnly()` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Collections.Generic.IList`1<OSCsharp.Data.OscMessage> OSCsharp.Data.OscBundle::get_Messages().
Error: method `System.Collections.ObjectModel.ReadOnlyCollection`1<!0> System.Collections.Generic.List`1<System.Object>::AsReadOnly()` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Collections.Generic.IList`1<System.Object> OSCsharp.Data.OscPacket::get_Data().
Error: method `System.Text.Encoding System.Text.Encoding::get_ASCII()` doesn't exist in target framework. It is referenced from OSCsharp.dll at T OSCsharp.Data.OscPacket::ValueFromByteArray(System.Byte[],System.Int32&).
Error: method `System.Text.Encoding System.Text.Encoding::get_ASCII()` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Byte[] OSCsharp.Data.OscPacket::ValueToByteArray(T).
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at OSCsharp.Net.UDPReceiver.
Error: field `System.Net.IPAddress System.Net.IPAddress::Any` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::.ctor(System.Int32,System.Boolean).
Error: field `System.Net.IPAddress System.Net.IPAddress::Loopback` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::.ctor(System.Int32,System.Net.IPAddress,System.Boolean).
Error: method `System.Net.IPAddress System.Net.IPAddress::Parse(System.String)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::.ctor(System.String,System.Int32,System.Boolean).
Error: type `System.Net.Sockets.Socket` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: method `System.Void System.Net.IPEndPoint::.ctor(System.Net.IPAddress,System.Int32)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: method `System.Void System.Net.Sockets.UdpClient::.ctor(System.Net.IPEndPoint)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: field `System.Net.IPAddress System.Net.IPAddress::Any` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: method `System.Void System.Net.IPEndPoint::.ctor(System.Net.IPAddress,System.Int32)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.Socket` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.SocketType` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.ProtocolType` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: method `System.Void System.Net.Sockets.Socket::.ctor(System.Net.Sockets.AddressFamily,System.Net.Sockets.SocketType,System.Net.Sockets.ProtocolType)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.Socket` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.SocketOptionLevel` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.SocketOptionName` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: method `System.Void System.Net.Sockets.Socket::SetSocketOption(System.Net.Sockets.SocketOptionLevel,System.Net.Sockets.SocketOptionName,System.Int32)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.Socket` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: method `System.Void System.Net.Sockets.Socket::Bind(System.Net.EndPoint)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: method `System.Void System.Net.Sockets.UdpClient::.ctor()` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.Socket` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: method `System.Void System.Net.Sockets.UdpClient::set_Client(System.Net.Sockets.Socket)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: method `System.Void System.Net.Sockets.UdpClient::JoinMulticastGroup(System.Net.IPAddress)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: field `System.Net.IPAddress System.Net.IPAddress::Any` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: method `System.Void System.Net.IPEndPoint::.ctor(System.Net.IPAddress,System.Int32)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: method `System.Void System.Net.Sockets.UdpClient::.ctor(System.Net.IPEndPoint)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: method `System.IAsyncResult System.Net.Sockets.UdpClient::BeginReceive(System.AsyncCallback,System.Object)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Start().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Stop().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Stop().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Stop().
Error: method `System.Void System.Net.Sockets.UdpClient::DropMulticastGroup(System.Net.IPAddress)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Stop().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Stop().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Stop().
Error: method `System.Void System.Net.Sockets.UdpClient::Close()` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::Stop().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::endReceive(System.IAsyncResult).
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::endReceive(System.IAsyncResult).
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::endReceive(System.IAsyncResult).
Error: method `System.Byte[] System.Net.Sockets.UdpClient::EndReceive(System.IAsyncResult,System.Net.IPEndPoint&)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::endReceive(System.IAsyncResult).
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::endReceive(System.IAsyncResult).
Error: method `System.IAsyncResult System.Net.Sockets.UdpClient::BeginReceive(System.AsyncCallback,System.Object)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver::endReceive(System.IAsyncResult).
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at OSCsharp.Net.UDPReceiver/UdpState.
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at OSCsharp.Net.UDPReceiver/UdpState.
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Net.Sockets.UdpClient OSCsharp.Net.UDPReceiver/UdpState::get_Client().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Net.Sockets.UdpClient OSCsharp.Net.UDPReceiver/UdpState::get_Client().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver/UdpState::set_Client(System.Net.Sockets.UdpClient).
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver/UdpState::set_Client(System.Net.Sockets.UdpClient).
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver/UdpState::.ctor(System.Net.Sockets.UdpClient,System.Net.IPEndPoint).
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPReceiver/UdpState::.ctor(System.Net.Sockets.UdpClient,System.Net.IPEndPoint).
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at OSCsharp.Net.UDPTransmitter.
Error: method `System.Net.IPAddress System.Net.IPAddress::Parse(System.String)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPTransmitter::.ctor(System.String,System.Int32).
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPTransmitter::Connect().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPTransmitter::Connect().
Error: method `System.Void System.Net.Sockets.UdpClient::.ctor()` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPTransmitter::Connect().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPTransmitter::Connect().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPTransmitter::Connect().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPTransmitter::Connect().
Error: method `System.Void System.Net.Sockets.UdpClient::Connect(System.Net.IPAddress,System.Int32)` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPTransmitter::Connect().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPTransmitter::Close().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPTransmitter::Close().
Error: method `System.Void System.Net.Sockets.UdpClient::Close()` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPTransmitter::Close().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPTransmitter::Close().
Error: type `System.Net.Sockets.UdpClient` doesn't exist in target framework. It is referenced from OSCsharp.dll at System.Void OSCsharp.Net.UDPTransmitter::Send(OSCsharp.Data.OscPacket).

**Comment by valyard** [comment]
Delete Modules/TUIO folder for now.

**Comment by valyard** [comment]
Can you try with these changes?
https://github.com/TouchScript/TouchScript/tree/develop
I don't have a machine with SDK set up.

**Comment by asoft2013** [comment]
Sorry, Valentin, do you have fixed unity package. I'm confusing to build this one from source...

**Comment by valyard** [comment]
Try this: [TouchScript.uwp.fix.unitypackage.zip](https://github.com/TouchScript/TouchScript/files/74434/TouchScript.uwp.fix.unitypackage.zip)

**Comment by asoft2013** [comment]
Now everything is fine! С наступающим!!! Happy New Year!!!
