### ISSUE TITLE
Disabling Gesture MonoBehaviour causes gesture to become unresponsive

### ISSUE THREAD

**Issue by nicetrysean** [TouchScript/TouchScript#199]
As it says on the tin, it would seem when disabling any Gesture MonoBehaviour in TouchScript 7, it will become unresponsive indefinitely.

**Comment by oafkad** [comment]
That's by design and was in the update notes.

to make things stop registering clicks:
Use: .INTERNAL_SetState(Gesture.GestureState.Failed); 

to make things start registering them again.
.INTERNAL_SetState(Gesture.GestureState.Possible); 

Hope that helps :).

**Comment by nicetrysean** [comment]
Oh I must have missed it! Thank you for your patience :~)

**Comment by oafkad** [comment]
It's cool. I went through the same thing and was confused for a solid half hour or so.

**Comment by valyard** [comment]
This is actually not intended and as far as I can see was added in this commit: https://github.com/TouchScript/TouchScript/commit/063818ddfe0f44d11821195045ebd114bb16fd43
Can you guys try this fix?
https://github.com/TouchScript/TouchScript/commit/b8c78faa78d1108871219d425f063838d6eb8db2

**Comment by oafkad** [comment]
Ah my apologies then.

Changed: When disabling gestures can now change state only to Failed.

I had seen this and it coincided with the error. Since there was no mention of enabling setting the gesture back to possible in the notes.

**Comment by oafkad** [comment]
@valyard I tested your fix and it works :). I can disable components and enable them and have the state renew.

So yeah, now it works just like the older unity did.
