### ISSUE TITLE
Documentation won't load because of constant reloading

### ISSUE THREAD

**Issue by kennypu** [TouchScript/TouchScript#202]
documentation pages won't load due to bug on page? It will constantly reload. This will also cause Visual Studio to freeze up as it can't do anything if the help page is followed through in a class.

Reproduce in browser: 
1. visit a documentation page, eg: http://touchscript.github.io/docs/Index.html?topic=html/T_TouchScript_Gestures_TransformGesture.htm 

Reproduce Visual Studio freeze
1. open up a class (eg. TransformGesture.cs)
2. visit the helpURL
3. VS freezes.

**Comment by valyard** [comment]
It looks like Github changed something in their iFrame handling. 
Changed docs formatting and reuploaded. Help URLs unfortunately changed and are reflected in this commit: 82704c09.
