### ISSUE TITLE
TransformGesture stops working when disabling and then re-enabling a world canvas

### ISSUE THREAD

**Issue by dinkeytomltd** [TouchScript/TouchScript#203]
[TouchScriptWin7Test.zip](https://github.com/TouchScript/TouchScript/files/93631/TouchScriptWin7Test.zip)

**Comment by valyard** [comment]
It seems that you don't have an UILayer set up like this
![2016-01-18 04-24-53 2 unity - touchscriptwin7test - pc mac linux standalone opengl 4 1](https://cloud.githubusercontent.com/assets/210516/12381475/993310b0-bd9b-11e5-840f-a309d6800078.png)
I tried disabling and enabling canvases and TransformGesture seemed to be working.

**Comment by dinkeytomltd** [comment]
I have the layer set up like that in my original project, but it's still not working for me when I disable or enable a WorldCanvas Object with Transform Gesture.
https://drive.google.com/file/d/0BwAC6q7_gz1QZ1Y1bF96SnUzeE0/view?usp=sharing

**Comment by valyard** [comment]
I'm sorry, can you provide steps to reproduce the behavior you are talking about?
I see two photos with canvases in world space but the transform gesture which is moving everything is on Scene game object.

**Comment by dinkeytomltd** [comment]
If you expand the 'Scene' gameobject and the 'Container' you will see that there are some World Space canvases. Press the lock icon next to the image and it should change to an unlock and that will enable it to be transformed, now select the 'Photo' in the hierarchy and disable and then enable the object. The buttons will be interactive, but the transform gesture will stop working. The same happens when you disable the container and then re-enable. However I've noticed that it still works when you move the 'Container' object outside of the 'Scene' object. So it seems to be a problem with putting a FullScreen Layer on a parent container. 
I'm currently uploading a video of it.

**Comment by valyard** [comment]
It seems that in uploaded configuration UI elements don't get touches at all. Even lock button is not clickable. Seems to be something with layer ordering.

**Comment by dinkeytomltd** [comment]
https://drive.google.com/file/d/0BwAC6q7_gz1QdHkwbTNPNUljQkU/view?usp=sharing

**Comment by valyard** [comment]
Right. I figured out what's wrong and it seems that I messed up big with one change in 7.0. The 3 gestures you have there in the hierarchy subscribe to FrameFinished event and whoever does it first will most likely trigger when you drag. If a gesture is disabled it unsubscribes and by subscribing later when enabled it becomes the last one in the list. It seems that I'll have to revert a big code change...

Accidentally I fixed another bug with layer order which I just uploaded as a part of version 7.1.

**Comment by valyard** [comment]
Can you try your project with these fixes?
https://github.com/TouchScript/TouchScript/tree/dev-8.0

**Comment by valyard** [comment]
@dinkeytomltd so, it works?

**Comment by dinkeytomltd** [comment]
Yes, it works

**Comment by dinkeytomltd** [comment]
It seems to block the ScreenScaleGesture.

**Comment by valyard** [comment]
Is this reproducible with the same project?

**Comment by dinkeytomltd** [comment]
Yes, it the same project

**Comment by dinkeytomltd** [comment]
Although when I import an earlier scene, it seems to work properly.

**Comment by valyard** [comment]
Are you sure you are using the latest TouchScript files?
If you still have the issue can you upload the new project and provide steps to reproduce please.

**Comment by dinkeytomltd** [comment]
Yes, I am using the latest files
https://drive.google.com/file/d/0BwAC6q7_gz1QOXMyMWZwTFBXWVE/view?usp=sharing

**Comment by valyard** [comment]
Seems to work fine. What do I do to break it?

**Comment by dinkeytomltd** [comment]
I don't know. It must be something to do with my Editor
