### ISSUE TITLE
TapGesture is not recognized on object with multiple gestures using fake touch points

### ISSUE THREAD

**Issue by dinkeytomltd** [TouchScript/TouchScript#205]
In the 'Cube' demo, import the prefabs from the 'Taps' demo and place them in front of the RenderToTexture Camera. Play and try tapping the cubes, it will always be recognized as a LongPress Gesture, however tapping the table works. I've had this problem when I wrote my own similar code. It seems that it could be Unity being too slow.
I've shared one from a demo I did in November, but have since adopted your method as it is much better.
https://drive.google.com/file/d/0BwAC6q7_gz1QYURQQ0ozeEVmaUE/view?usp=sharing

**Comment by valyard** [comment]
Can you provide an example project for this behavior?

**Comment by dinkeytomltd** [comment]
Sorry, I meant cube demo.
https://drive.google.com/open?id=0BwAC6q7_gz1QbkFteHpBMzVJLTg

**Comment by valyard** [comment]
It's because of this line: https://github.com/TouchScript/TouchScript/commit/14767c039de761a35fb7146c24dacffd765f1416#diff-60e469dcf2ca4bf717303748f2267354L32
In the example main camera is a different one. I changed the example to reflect this.
