### ISSUE TITLE
On the Wiki, most links result in 404.

### ISSUE THREAD

**Issue by JamesAMD** [TouchScript/TouchScript#206]
Most links in wiki pages result in 404 error.
Most notably in [Gestures](https://github.com/TouchScript/TouchScript/wiki/Gestures) and [Layers](https://github.com/TouchScript/TouchScript/wiki/Layers), where there's links to documentation pages for classes.

**Comment by valyard** [comment]
Changed docs format recently. Will update the links soon.

**Comment by valyard** [comment]
OK, seems mostly fixed.
