### ISSUE TITLE
How to check the current touched GameObject?

### ISSUE THREAD

**Issue by ankit7sethi** [TouchScript/TouchScript#207]
I tried using TouchManager.Instance.GetHitTarget, but couldn't get the GameObject which it is touching.

**Comment by RicardoGuzmanVelasco** [comment]
In the Tap Example, the cube checks if is touched. Take a look.

**Comment by valyard** [comment]
You probably are not doing it TouchScript way.
You need to add a gesture to an object. This gesture will get hits from touches and react. Your code should subscribe to gesture's events and do something when they fire. In this case this question will be irrelevant.

But in general TouchManager.Instance.GetHitTarget should work. It returns Hit object which has Target property you can use.
