### ISSUE TITLE
TUIO input script has return wrong position coordinates for objects

### ISSUE THREAD

**Issue by mereld** [TouchScript/TouchScript#210]
Unity
TUIO input script

Touch Visualiser shows the mark in the right position on screen, but coordinates in "Touch.position" always static (only for objects, with touches - all ok).

using System.Collections.Generic;
using TouchScript;
using TouchScript.Gestures;
using UnityEngine;

public class compass_recogniser : MonoBehaviour
    {

    private void OnEnable()
        {
            if (TouchManager.Instance != null)
            {
                TouchManager.Instance.TouchesBegan += touchesBeganHandler;
        }
        }

        private void OnDisable()
        {
            if (TouchManager.Instance != null)
            {
                TouchManager.Instance.TouchesBegan -= touchesBeganHandler;
         
        }
        }
    private void touchesBeganHandler(object sender, TouchEventArgs e)
        {
            foreach (var point in e.Objects)
            {
            
            if (point.Tags.ToString().Equals("TUIO, Object, compass"))
              {
                
                Debug.Log(point.Tags.ToString());
                Debug.Log(point.Position.x);
                Debug.Log(point.Position.y);
             }
            }
        }
    }

Output:
TUIO, Object, compass
-161.0938
1131

**Comment by mereld** [comment]
if i use TouchManager.Instance.TouchesMoved - has return coordinates perfectly
TouchManager.Instance.TouchesBegan - position always static.

**Comment by valyard** [comment]
What do you mean by "static"?
TouchesBegan is an event when a touch first appears on the surface, it should have the position of contact when you touch the surface. TouchesMoved update this position accordingly.
