### ISSUE TITLE
Multitouch: Touch remains on screen without touching (Surface, WebGL)

### ISSUE THREAD

**Issue by johannes86** [TouchScript/TouchScript#212]
Hello,

I am using the newest Release of TouchScript for a Unity Project with WebGL Build. The Build runs on Windows 10 Surface in Chromium.
After doing a multitoch gesture like "pinch to zoom", sometimes a touch remains on the Screen (visualized by Touch Visualizer). When I touch the Screen with only one finger then, The two-finger gesture is activated (pinch to zoom) because the other touch seems to be still active.

You can reproduce the issue with the Camera-Example in a webGL-Build. Zoom a few times. I think it occurs when the touches get very Close to each other. Or use even more fingers on the Screen.
Cannot reproduce it in a Windows x86 build.

**Comment by valyard** [comment]
What Unity version do you use?

**Comment by valyard** [comment]
I am not able to reproduce this using MS Surface Pro 3 and Unity 5.3.3p2.
Can you record a video of the issue?
