### ISSUE TITLE
Touch Visualizer prevents mouse multi-touch simulation

### ISSUE THREAD

**Issue by Cross22** [TouchScript/TouchScript#215]
Following the tutorials I added the TouchVisualizer prefab to the scene. Then I used Alt-Click to simulate multi-touch events on my PC. While the circles do appear, processing via a Transformer Gesture does not work in that case. After trying various things for half an hour I eventually deleted the TouchVisualizer and now I could simulate multi touch gestures with the mouse.
It would be helpful to document this behavior!

**Comment by valyard** [comment]
It actually should work with TouchVisualizer. What touch device do you have? Are you testing in the editor?
