### ISSUE TITLE
32-bit Unity application prompted errors after quit (Windows 7 x64)

### ISSUE THREAD

**Issue by musiko** [TouchScript/TouchScript#216]
**Platform: Windows 7 64-bit
Unity version: v5.3.4 (32-bit)
Touchscript version: 8.1**

**Test case:**
1. Create "Touch Manager" gameObject, add "Touch Visualizer" prefab, add "Camera Layer" to Main Camera
2. Export Windows standalone application with default player settings
3. Run the application.
4. Quit the program with Ctrl+F4
5. Windows popped "xxx.exe has stopped working" and error log folder is created.

**Error logs: (_error.log_ and _output_log.txt_)**
https://gist.github.com/musiko/a7e543fa0ea0cd60baec12cc5ce129cd

**Comment by musiko** [comment]
I searched onTouchscript forum and found a [thread](http://touchprefab.com/viewtopic.php?f=4&t=24424)  regarding the similar issue. I tested the Touchscript version by valyard. Touch did not work, prompting DllNotFoundException:
https://gist.github.com/musiko/74570a3570615feb4555132998a7c529

**Comment by yty** [comment]
@valyard 

+1 ...

I also have the same problem.

Platform: Windows 8 64-bit
Unity version: v5.3.4f1 (32-bit)
Touchscript version: 8.1

**Comment by valyard** [comment]
I'm not able to reproduce it o.O
Do you guys still get DLL not fount exception?
Does *_Data/Plugins folder contain WindowsTouch.dll?

**Comment by valyard** [comment]
Moving discussion back to https://github.com/TouchScript/TouchScript/issues/200
