### ISSUE TITLE
Single tap and double tap on the same object

### ISSUE THREAD

**Issue by theoxuan** [TouchScript/TouchScript#217]
According to this wiki:
[https://github.com/TouchScript/TouchScript/wiki/Gestures#requiring-a-gesture-to-fail](url)
single tap and double tap can be compatible with each other on the same object, just set the `singleTap.RequireGestureToFail = doubleTap`, which is what I did. But it seems either single tap blocks double tap or vice versa, even though I've tried tweaking the `TimeLimit` field and separating them on different sub-objects.
Am I missing something or doing wrong?
![image](https://cloud.githubusercontent.com/assets/5442563/15525830/c0f41954-225f-11e6-9354-8ff98d797d3f.png)

```
public class TapTest : MonoBehaviour {

	public TapGesture doubleTap;
	public TapGesture singleTap;

    void Start()
    {
        //doubleTap = gameObject.AddComponent<TapGesture>();
        //singleTap = gameObject.AddComponent<TapGesture>();
        //singleTap.RequireGestureToFail = doubleTap;
        //doubleTap.NumberOfTapsRequired = 2;
        doubleTap.Tapped += DoubleTapOnTapped;
        singleTap.Tapped += SingleTapOnTapped;
    }

    private void SingleTapOnTapped(object sender, EventArgs eventArgs)
    {
        Debug.Log("single");
    }

    private void DoubleTapOnTapped(object sender, EventArgs eventArgs)
    {
        Debug.Log("double");
    }
}

```

I desperately need this to work. I need single-tap to pause/resume player and double-tap to enter fullscreen.
(Sorry if it's not an issue)

**Comment by houzy** [comment]
I really want to know it too!

**Comment by theoxuan** [comment]
@houzy 
I've figured out somehow :dancer: 

![image](https://cloud.githubusercontent.com/assets/5442563/15666900/e16e849a-2745-11e6-8a6e-62bcf77bd86d.png)

The **Limit Time** has to be **0.3** or greater. That's the key. Anyway 0.3s is acceptable. :smile: 

However that is not mentioned in documents.
Hope this helps.

**Comment by houzy** [comment]
Great! Thanks @theoxuan
