### ISSUE TITLE
Canvas Screen Space Overlay Intermittently Not Working

### ISSUE THREAD

**Issue by charlespalen** [TouchScript/TouchScript#224]
First off; great work on this project. It's really amazing. Maybe I'm just missing something simple. I've attached the project/scene described in detail below.

Issue Description:
I cannot get any new scenes with a single Canvas set to screen space overlay to properly receive touches on UI elements within the canvas. 

I've examined the "photos" example in depth and completely modified it to remove everything except the canvas containing the cat images, set that to screen space overlay, and it will work.  However in the same example if you take the Scene -> ScreenSpaceCanvas -> Panel and remove the horizontal layout group; then modify one of the buttons to remove the UI Gesture, then add a Transform Gesture and a Transformer you will be unable to drag or transform any of the buttons.  You can use two touchpoints and try and rotate the button; but you will get an error:

transform.localScale assign attempt for 'Image' is not valid. Input localScale is { NaN, NaN, NaN }.
UnityEngine.Transform:set_localScale(Vector3)
TouchScript.Gestures.TransformGesture:ApplyTransform(Transform) (at Assets/TouchScript/Scripts/Gestures/TransformGesture.cs:132)

With a fresh setup of a canvas and the Touchscript UI Layer all elements will have this same behavior which I will describe below.

Platforms Tested On:
Windows 8.1 with Unity 5.3.5f1
  Touchscript 7.1 - 8.2
Windows 8.1 with Unity 5.4
  Touchscript 8.2

Steps to Reproduce:
1. Import the entire Touchscript Unitypackage.
2. Create a new scene.
3. Add UI -> Image (this will automatically add a canvas and Event System)
4. Delete the automatically added EventSystem. (Because the Touchscript UI layer will auto add it once we add it later).
5. Create a new blank object at the root of the project named "TouchScript" add the "Touch Manager" script to this object with all defaults selected.
6.Create another blank object at the root of the project and add the Touchscript UI Layer to it.
7. On the image inside of the Canvas add the Transform Gesture script and Transformer script to it. Also assign a sprite of some sort to the image so you can know if you are actually rotating it.
8. Optionally add the "Touch Visualizer" prefab to the sceene
9. Check the "TouchScript" object to ensure that it has populated with the "UI Layer" as one of the Touch Layers.
10. Run the project. You wont be able to do anything to the image except try and rotate it using two points at which point you'll get the runtime error specified above as it sporadically transforms the Z rotation only on the images rect trasnform.  Here's the full stack trace:

transform.localScale assign attempt for 'Image' is not valid. Input localScale is { NaN, NaN, NaN }.
UnityEngine.Transform:set_localScale(Vector3)
TouchScript.Gestures.TransformGesture:ApplyTransform(Transform) (at Assets/TouchScript/Scripts/Gestures/TransformGesture.cs:132)
TouchScript.Behaviors.Transformer:transformHandler(Object, EventArgs) (at Assets/TouchScript/Scripts/Behaviors/Transformer.cs:63)
TouchScript.Utils.EventHandlerExtensions:InvokeHandleExceptions(EventHandler`1, Object, EventArgs) (at Assets/TouchScript/Scripts/Utils/EventHandlerExtensions.cs:28)
TouchScript.Gestures.Base.TransformGestureBase:onChanged() (at Assets/TouchScript/Scripts/Gestures/Base/TransformGestureBase.cs:466)
TouchScript.Gestures.Gesture:set_State(GestureState) (at Assets/TouchScript/Scripts/Gestures/Gesture.cs:266)
TouchScript.Gestures.Gesture:setState(GestureState) (at Assets/TouchScript/Scripts/Gestures/Gesture.cs:946)
TouchScript.Gestures.Base.TransformGestureBase:touchesMoved(IList`1) (at Assets/TouchScript/Scripts/Gestures/Base/TransformGestureBase.cs:424)
TouchScript.Gestures.Gesture:INTERNAL_TouchesMoved(IList`1) (at Assets/TouchScript/Scripts/Gestures/Gesture.cs:774)
TouchScript.GestureManagerInstance:doUpdateMoved(Gesture, IList`1) (at Assets/TouchScript/Scripts/GestureManagerInstance.cs:224)
TouchScript.GestureManagerInstance:update(IList`1, Action`1, Action`2) (at Assets/TouchScript/Scripts/GestureManagerInstance.cs:280)
TouchScript.GestureManagerInstance:touchesMovedHandler(Object, TouchEventArgs) (at Assets/TouchScript/Scripts/GestureManagerInstance.cs:572)
TouchScript.Utils.EventHandlerExtensions:InvokeHandleExceptions(EventHandler`1, Object, TouchEventArgs) (at Assets/TouchScript/Scripts/Utils/EventHandlerExtensions.cs:28)
TouchScript.TouchManagerInstance:updateUpdated(List`1) (at Assets/TouchScript/Scripts/TouchManagerInstance.cs:653)
TouchScript.TouchManagerInstance:updateTouches() (at Assets/TouchScript/Scripts/TouchManagerInstance.cs:766)
TouchScript.TouchManagerInstance:Update() (at Assets/TouchScript/Scripts/TouchManagerInstance.cs:525)

![touchscript_8_13_2016](https://cloud.githubusercontent.com/assets/4041571/17645255/30b4bb20-616e-11e6-8f4b-2e63f132805d.jpg)

[TouchscriptStepByStepUnityProject.zip](https://github.com/TouchScript/TouchScript/files/416747/TouchscriptStepByStepUnityProject.zip)

**Comment by valyard** [comment]
There's indeed a bug in CanvasProjectionParams.ProjectTo method.
You can use ScreenTransformGesture instead of TransformGesture now but I'm in the process of reengineering UI support which is almost done in alpha branch. You can try it there if you want (but there might be the same bug, I need to check).

**Comment by charlespalen** [comment]
I tested every non-working instance I had replacing TransformGesture with ScreenTransformGesture. It works!  Sorry for overlooking ScreenTransformGesture. I'm going to close the issue as ScreenTransformGesture is a work-around.  If you'd like to keep it open, please re-open it.

Thanks again for all of your hard work.
