### ISSUE TITLE
Transform Gesture Delta Scale is null

### ISSUE THREAD

**Issue by malitvin** [TouchScript/TouchScript#227]
When attempting to Scale a GameObject (aka pinch to zoom). I am trying to get the TransformGesture DeltaScale float variable during a _Transformed_  EventHandler and the value will always be _NaN_ . When attempting to get the value during the _TransformStarted_ event handler the value will be 1.

**Comment by valyard** [comment]
Can you check the Normal on TransformGesture? You can get this if gesture Normal is perpendicular to layer Normal.
