### ISSUE TITLE
Cannot open Tap_Breaker.cs. from repository

### ISSUE THREAD

**Issue by BuddhikaRJ** [TouchScript/TouchScript#229]
I tried to use your tutorial on[ Tap gesture](https://github.com/TouchScript/TouchScript/wiki/Tutorial.-Tap-Gesture.). but the Tap_Breaker.cs cannot be accessed from the given[ link](https://github.com/TouchScript/TouchScript/blob/develop/UnityPackages/TouchScript/Assets/TouchScript/Examples/General/Tap/Scripts/Tap_Breaker.cs).  
![scr](https://cloud.githubusercontent.com/assets/17719295/21472172/727ebac2-caf2-11e6-9b10-f1f55210b791.jpg)

Your attention and help is highly valued at the moment.

**Comment by valyard** [comment]
Develop branch is in... development at the moment. 
It is better to download the package and look at examples. Tap example is what you are looking for.
