### ISSUE TITLE
IL2CPP error when building for iOS

### ISSUE THREAD

**Issue by adre84** [TouchScript/TouchScript#232]
Hello i am unable to build for iOS.
Unity 5.5.0f3

IL2CPP error for type 'TouchScript.Gestures.ScreenTransformGesture' in assembly '/Users/project-path/Temp/StagingArea/Data/Managed/Assembly-CSharp.dll'
Additional information: Build a development build for more information. Interface TouchScript.Gestures.CKGMHCCAJGE method System.Void TouchScript.Gestures.CKGMHCCAJGE::HKMDAFMLMLL(System.EventHandler`1<System.EventArgs>) not implemented on non-abstract class TouchScript.Gestures.ScreenTransformGesture

**Comment by valyard** [comment]
Doesn't seem to be a TouchScript issue. 
Can you test with TouchScript examples project?
