### ISSUE TITLE
Is there a way to start a gesture outside a gameobject

### ISSUE THREAD

**Issue by IJsLauw** [TouchScript/TouchScript#235]
And still detect the gesture once the gesture goes over the gameobject?

In my game I want to be able to push/move a (airhocky paddle) even when the user drags his finger from outside the object. As soon as the user's finger is over the object the object should start moving as if the touch began on the object on that moment... I want to know if there is a way to do this using the existing gestures or how I can implement this myself.

Thanks!

**Comment by valyard** [comment]
By default the object which got the first touch owns it. Gestures can't exist without a target object.
Your case is kinda hard in the current system. I'm not sure, you can probably try to do the following:
1. Add a Transform gesture to the paddle.
1. Catch a touch with a FullscreenLayer.
1. Every frame check if the touch is over the paddle (`touch.GetOverData()`).
1. If it is, cancel the touch returning it to the system. In this case the paddle will catch the touch and the gesture will start normally. (`TouchManager.Instance.CancelPointer(touch.Id, true)`)

**Comment by IJsLauw** [comment]
Thanks, I will have a go at it and see how it responds!
