### ISSUE TITLE
How to find the TouchScript version number

### ISSUE THREAD

**Issue by NatDau** [TouchScript/TouchScript#236]
I have a project built on Unity 5.3.2fa with older version of TouchScript( before version 7.1).  We have the  TouchScript UnityPackages.   But there is no AssetStore\ProjectSettings\ProjectVersion.txt file exist.
Is there a way to identify the TouchScript version number?

**Comment by valyard** [comment]
The only way is to use `TouchManager.VERSION`. But I'm not sure at what point it was added. Probably somewhere along 6.0.
