### ISSUE TITLE
App closing/crashing if using stylus input pen

### ISSUE THREAD

**Issue by ilmatematico** [TouchScript/TouchScript#238]
Using windows 10 and  stylus pen (surface like) the standalone application suddenly close on the firt touch, it does not appen with mouse or touch.

**Comment by valyard** [comment]
Can you attach Unity log?
What device are you using?

**Comment by uek06** [comment]
Hello, I tried to build the TouchScript 9.0 ALPHA 3 examples scene with Unity. I have a Surface Pro 4 with Windows 10. 
The exe file built with Unity works well when i use the mouse or my fingers, but when i use the microsoft surface pen the standalone app closes immediatly.
Please find attached the output_log `Initialize engine version: 5.6.0f3 (497a0f351392)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Intel(R) HD Graphics 520 (ID=0x1916)
    Vendor:   Intel
    VRAM:     2111 MB
    Driver:   20.19.15.4463
Begin MonoManager ReloadAssembly
Platform assembly: C:\Users\\Documents\touchscriptex_Data\Managed\UnityEngine.dll (this message is harmless)
Loading C:\Users\\Documents\touchscriptex_Data\Managed\UnityEngine.dll into Unity Child Domain
Platform assembly: C:\Users\\Documents\touchscriptex_Data\Managed\Assembly-CSharp.dll (this message is harmless)
Loading C:\Users\\Documents\touchscriptex_Data\Managed\Assembly-CSharp.dll into Unity Child Domain
Platform assembly: C:\Users\\Documents\touchscriptex_Data\Managed\UnityEngine.UI.dll (this message is harmless)
Loading C:\Users\\Documents\touchscriptex_Data\Managed\UnityEngine.UI.dll into Unity Child Domain
Platform assembly: C:\Users\\Documents\touchscriptex_Data\Managed\UnityEngine.Networking.dll (this message is harmless)
Loading C:\Users\\Documents\touchscriptex_Data\Managed\UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: C:\Users\\Documents\touchscriptex_Data\Managed\UnityEngine.Analytics.dll (this message is harmless)
Loading C:\Users\\Documents\touchscriptex_Data\Managed\UnityEngine.Analytics.dll into Unity Child Domain
Platform assembly: C:\Users\\Documents\touchscriptex_Data\Managed\OSCsharp.dll (this message is harmless)
Loading C:\Users\\Documents\touchscriptex_Data\Managed\OSCsharp.dll into Unity Child Domain
Platform assembly: C:\Users\\Documents\touchscriptex_Data\Managed\TUIOsharp.dll (this message is harmless)
Loading C:\Users\\Documents\touchscriptex_Data\Managed\TUIOsharp.dll into Unity Child Domain
- Completed reload, in  0.038 seconds
Platform assembly: C:\Users\\Documents\touchscriptex_Data\Managed\System.Core.dll (this message is harmless)
Platform assembly: C:\Users\\Documents\touchscriptex_Data\Managed\System.dll (this message is harmless)
desktop: 2736x1824 60Hz; virtual: 2736x1824 at 0,0
<RI> Initializing input.

XInput1_3.dll not found. Trying XInput9_1_0.dll instead...
<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 8.222359 ms
Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.909538 ms

Unloading 4 unused Assets to reduce memory usage. Loaded Objects now: 856.
Total: 0.924717 ms (FindLiveObjects: 0.053743 ms CreateObjectMapping: 0.036102 ms MarkObjects: 0.821743 ms  DeleteObjects: 0.011897 ms)

[TouchScript] Initialized Windows 8 pointer input.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

`

**Comment by valyard** [comment]
I see. The battery in my pen died and I can't find an AAAA battery anywhere. I guess I have to look harder now to test this...

**Comment by uek06** [comment]
Hi again, did you manage to find a new battery in order to test it ? Maybe if you give me some hint I would be able to look into the code.

**Comment by valyard** [comment]
Could you test this version? The pen works on my laptop.
[pentest.zip](https://github.com/TouchScript/TouchScript/files/1156691/pentest.zip)

**Comment by uek06** [comment]
Yes it's working with my laptop too 👍 thanks ! Are you going to put the fix in the 9.0alpha4 release or something ?

**Comment by valyard** [comment]
Yes, I'm going to combine all the fixes to alpha4 soon.

**Comment by valyard** [comment]
Fixed in https://github.com/TouchScript/TouchScript/releases/tag/9.0
