### ISSUE TITLE
Incompatibility With UniOSC

### ISSUE THREAD

**Issue by Anraksha** [TouchScript/TouchScript#239]
Hi,
Both in UniOSC  and Touchscript  the OSCSharp.dll is used But recently i found out that  (today) they are not the same version and when i use touchscript with unisoc the  button wont work in the build version (altough it work well in the  editor version ) If i remove your version the button will not work  and if i remove the uniosc version   it wont build  because  there is  this problem :

Assets/UniOSC/Scripts/UniOSCTransmitter.cs(82,84): error CS1729: The type `OSCsharp.Net.UDPTransmitter' does not contain a constructor that takes `3' arguments 

I've enter in contact with  the developper of UniOSC  and he said to me that you both tried to have the same version of OSCSharp.dll  but when i look  on both of your DLL i found out that there is your dll which  is from 6 august 2016 and weight 20992 bytes  and the one from uniosc is from 22 december 2016 and weight 21504 bytes

Cordially,
Anraksha

**Comment by Anraksha** [comment]
![capture](https://cloud.githubusercontent.com/assets/23458480/23804236/82cba5d2-05b9-11e7-9314-3443b4e2af66.PNG)

**Comment by valyard** [comment]
Hm. Do you actually need OSC/TUIO functionality in TouchScript?
If not, you can just delete TUIOSharp and TuioInput to get rid of this dependency.

**Comment by Anraksha** [comment]
Thanks for the reply i thinked that TuioSharp was used by the touchscript and i didn't think to delete it
