### ISSUE TITLE
TouchScript 9.0 Alpha 2 compatibility issue with Windows 7

### ISSUE THREAD

**Issue by NatDau** [TouchScript/TouchScript#241]
Just download the TouchScript 9.0 Alpha 2 because the latest release TouchScript 8.2 crashes on quit.
Build and run the example, there are error messages on the development console, and touch script doesn't work on the build executable. 
------------------------------Development Console--------------------------------------------------
Failed to load 'F:/TestTouchScriptAlpha/TestAlpha_Data/Plugins/WindowsTouch.dll' with error 'The specified procedure could not be found.
'.
Failed to load 'F:/TestTouchScriptAlpha/TestAlpha_Data/Plugins/WindowsTouch.dll' with error 'The specified procedure could not be found.
'.
DllNotFoundException: F:/TestTouchScriptAlpha/TestAlpha_Data/Plugins/WindowsTouch.dll

**Comment by valyard** [comment]
I was pointed out that the resulting DLLs depended on VC++ redistributable.
But I was sure that I fixed this here: https://github.com/TouchScript/TouchScript/issues/200
Can you check if you have VC++ redistributable installed on your machine?

**Comment by NatDau** [comment]
I think so.
-VC 2015 C++ information
http://prntscr.com/ep5irn

-VC 2015 general version info
http://prntscr.com/ep5h8y

**Comment by demskiy** [comment]
I'd like to add here that a user with Windows 2008 R2 reported the same issue. Is there a workaround for such users? The game went live with this issue and I have no idea how to fix it. Unity 5.6, tried both x86 and x86_64 builds.

**Comment by valyard** [comment]
At this point I don't know what's going on. I clearly see no dependencies on VC++ redistributable in the resulting DLL. Does anyone know what I am missing?

![2017-04-26_06-33-21](https://cloud.githubusercontent.com/assets/210516/25412077/a893f624-2a4a-11e7-8cce-6ecdd01da393.png)
Left — old, right — new.

**Comment by demskiy** [comment]
Is there a chance that WindowsTouch.dll uses WinAPI method that was introduced in Windows 8? The common thing between Win7 and Win 2008 R2 is that they are pretty old.

**Comment by demskiy** [comment]
Here is the screen from Windows 7 (not working):
![windowstouch_dw](https://cloud.githubusercontent.com/assets/6223527/25431643/1838e270-2a8a-11e7-8f8e-caa3a0b1a06f.png)
Here is the screen from Windows 8.1 (working):
![image](https://cloud.githubusercontent.com/assets/6223527/25431711/5ce70e10-2a8a-11e7-8025-0bd8746bb68d.png)

**Comment by valyard** [comment]
Can you save both as DWIs and attach?

**Comment by demskiy** [comment]
Please find 4 dwi files in [this archive](https://drive.google.com/file/d/0B85wj5RcrL83Mjd2MDN0NXdZdlE/view?usp=sharing) - Win7 x86/64 (not working) and Win8.1 x86/64 (working despite errors).

**Comment by valyard** [comment]
![2017-04-27_23-12-52](https://cloud.githubusercontent.com/assets/210516/25502397/140e95f8-2b9f-11e7-84c0-18a246768b2c.png)
Must be this guy.

**Comment by demskiy** [comment]
If GetPointerInfo() is actually used in WindowsTouch.dll, then it is at least one culprit, since it was introduced in Windows 8 / Windows Server 2012. However, there could be more culprits.

**Comment by valyard** [comment]
@demskiy Can you please test this?
Branch: dev-win7-touch
Attached built DLLs.
[WindowsTouch.zip](https://github.com/TouchScript/TouchScript/files/962961/WindowsTouch.zip)

One thing though — does the game use touch API at all? Windows 2008 R2 afaik doesn't have touch input.

**Comment by demskiy** [comment]
I tested both new versions of WindowsTouch.dll with x86 and 64 builds on Windows 7 64bit - both worked fine, congrats! I guess that release version of these dlls will be smaller?

**Comment by valyard** [comment]
Published the release version DLLs as a part of 9.0a3 — https://github.com/TouchScript/TouchScript/releases/tag/9.0alpha3

Also this question remains: does the game use touch API at all? Windows 2008 R2 afaik doesn't have touch input.

**Comment by demskiy** [comment]
Great news! It's not quite clear what do you mean by "Touch API", but we use touch gestures like tap, swipe and rotate, FullScreen and Standard layers + Unity UI since upgrade to TouchScript 9.0. The game is cross-platform, so it's available on PC and mobile including touch, mouse and gamepad inputs. As for Windows 2008 R2 - I really don't know how it works there since I knew about problems on this OS from one of our players. Does it answer your question?

**Comment by valyard** [comment]
I guess on Windows 2008 R2 the game only uses mouse, right?
Most likely the DLL will still not work on this os since it's older than Windows 7.

**Comment by demskiy** [comment]
Yes, my best guess is that Win 2008 R2 has mouse only. I'll post an update to this issue whenever that user checks on his Win 2008 R2.

**Comment by demskiy** [comment]
The user with Windows Server 2008 R2 Datacenter SP1 reported back that now everything works fine. He was using 32 bit version, I don't know if it applies to 64 bit version.
