### ISSUE TITLE
Not an error Just simple warning in Unity's console

### ISSUE THREAD

**Issue by asoft2013** [TouchScript/TouchScript#242]
Assets/TouchScript_8_2/Editor/Gestures/Base/PinnedTransformGestureBaseEditor.cs(31,30): warning CS0618: `UnityEditor.SerializedObject.UpdateIfDirtyOrScript()' is obsolete: `UpdateIfDirtyOrScript has been deprecated. Use UpdateIfRequiredOrScript instead.'

Assets/TouchScript_8_2/Editor/Gestures/Base/TransformGestureBaseEditor.cs(35,30): warning CS0618: `UnityEditor.SerializedObject.UpdateIfDirtyOrScript()' is obsolete: `UpdateIfDirtyOrScript has been deprecated. Use UpdateIfRequiredOrScript instead.'

Assets/TouchScript_8_2/Editor/Gestures/FlickGestureEditor.cs(36,30): warning CS0618: `UnityEditor.SerializedObject.UpdateIfDirtyOrScript()' is obsolete: `UpdateIfDirtyOrScript has been deprecated. Use UpdateIfRequiredOrScript instead.'

Assets/TouchScript_8_2/Editor/Gestures/GestureEditor.cs(83,30): warning CS0618: `UnityEditor.SerializedObject.UpdateIfDirtyOrScript()' is obsolete: `UpdateIfDirtyOrScript has been deprecated. Use UpdateIfRequiredOrScript instead.'

Assets/TouchScript_8_2/Editor/Gestures/LongPressGestureEditor.cs(30,30): warning CS0618: `UnityEditor.SerializedObject.UpdateIfDirtyOrScript()' is obsolete: `UpdateIfDirtyOrScript has been deprecated. Use UpdateIfRequiredOrScript instead.'

Assets/TouchScript_8_2/Editor/Gestures/TapGestureEditor.cs(35,30): warning CS0618: `UnityEditor.SerializedObject.UpdateIfDirtyOrScript()' is obsolete: `UpdateIfDirtyOrScript has been deprecated. Use UpdateIfRequiredOrScript instead.'

Assets/TouchScript_8_2/Editor/InputSources/InputSourceEditor.cs(20,30): warning CS0618: `UnityEditor.SerializedObject.UpdateIfDirtyOrScript()' is obsolete: `UpdateIfDirtyOrScript has been deprecated. Use UpdateIfRequiredOrScript instead.'

Assets/TouchScript_8_2/Editor/InputSources/MobileInputEditor.cs(24,30): warning CS0618: `UnityEditor.SerializedObject.UpdateIfDirtyOrScript()' is obsolete: `UpdateIfDirtyOrScript has been deprecated. Use UpdateIfRequiredOrScript instead.'

Assets/TouchScript_8_2/Editor/InputSources/MouseInputEditor.cs(24,30): warning CS0618: `UnityEditor.SerializedObject.UpdateIfDirtyOrScript()' is obsolete: `UpdateIfDirtyOrScript has been deprecated. Use UpdateIfRequiredOrScript instead.'

Assets/TouchScript_8_2/Editor/InputSources/StandardInputEditor.cs(37,30): warning CS0618: `UnityEditor.SerializedObject.UpdateIfDirtyOrScript()' is obsolete: `UpdateIfDirtyOrScript has been deprecated. Use UpdateIfRequiredOrScript instead.'

**Comment by valyard** [comment]
Is it 5.6?
