### ISSUE TITLE
Unity InputField and UIGesture

### ISSUE THREAD

**Issue by Ryumizuhi** [TouchScript/TouchScript#244]
Hi,
I have a problem when i using an inputField with UIGesture.
I have a button who shows a panel where it is my inputField. When I "click" on it, I have an NullReferenceException on the InputField. When I disable UIGesture, I have no more error but i can't interract with the inputField.
Thanks
![pbinputfield](https://cloud.githubusercontent.com/assets/27427262/25006908/f5d41310-205e-11e7-973f-9328c7c8fd93.png)

**Comment by valyard** [comment]
What Unity and TouchScript versions are you using? 
Can you send me a scene with your UI setup?

**Comment by Ryumizuhi** [comment]
Hello,
I use the version 5.5.4f1 of Unity but I don't no which version of
TouchScript I use. How can I known it when the project is open ?
I join you the scene where I have the problem.
Best regards
Marie

2017-04-26 1:45 GMT+02:00 Valentin Simonov <notifications@github.com>:

**Comment by Ryumizuhi** [comment]
the version of unity is 5.5.0f3

2017-04-26 8:00 GMT+02:00 Marie Rondeau <marierondeau3@gmail.com>:

**Comment by valyard** [comment]
Look at `TouchManager.VERSION`.

**Comment by Ryumizuhi** [comment]
Hello
The version of TouchScript is 8.2.


2017-04-26 18:43 GMT+02:00 Valentin Simonov <notifications@github.com>:

**Comment by valyard** [comment]
Works in 9.0.
