### ISSUE TITLE
TransformGesture doesn't work in hierachy

### ISSUE THREAD

**Issue by leopardodavid** [TouchScript/TouchScript#245]
Hi!, great job making touchscript, you are my hero :)

Second, I am having some issues with TransformGesture and PressGesture (and other gestures) when I want to implement them in a hierachy. More specific, I  can make it work with any kind of gestures when they're declared in the top level of the scene, but, when I try to do the same inside a sub-level inside the hierachy they simply don't recognize. I know my code is working because I can make work with the generic gestures (TouchManager.Instance.TouchesBegan += touchesBeganHandler; for example) but not the instantiated ones like TransformGesture or PressGesture. 

I follow the "Photos" Example to implement my own program but it is not working.

Here in the photo I explain where the gestures work and where they don't.
![122](https://cloud.githubusercontent.com/assets/18411412/26048781/2980b722-391e-11e7-81c8-07a4e75925a3.png)

If someone could give some ideas of how to solve this it would be great.
Thanks.

**Comment by valyard** [comment]
Your ContenedorTUIO object doesn't have a mean to intercept touches. Since you are using UI, you need to add an Interactive component to it like an Image or so. TableroAjedrez object probably got one of these.
