### ISSUE TITLE
Tutorial - Writing a custom gesture

### ISSUE THREAD

**Issue by IJsLauw** [TouchScript/TouchScript#246]
I'd like to do this tutorial, is there something coming anytime soon? Or could someone point me in the right direction?

https://github.com/TouchScript/TouchScript/wiki/Tutorial.-Writing-a-Custom-Gesture.

**Comment by valyard** [comment]
Unfortunately nothing is coming soon.
The best way to learn how to write a gesture is to look how other gestures are implemented.
