### ISSUE TITLE
Wrong touch coordinates after resolution change (Win7 - 9.0alpha3)

### ISSUE THREAD

**Issue by zerez** [TouchScript/TouchScript#248]
Hi,

this is not really a bug, but could be a problem for everyone who want to change the resolution at runtime. The problem is that after changing the resolution the touch points are at the wrong positions. I made a workaround by disabling and reenabling the _StandardInput_ so it reinitializes the _Windows7PointerHandler_ and finally calls _initScaling_ in it's base constructor again. Unfortunately this resulted in destroying the old StandardInput singleton instance, so I added another check inside StandardInput before destroying the instance (line 223), to prevent potentially missing references to this component.

`if (instance != null && instance != this) Destroy(instance);`

I think a better solution would be to provide a public function which can be called when a resolution change happens, to prevent everything getting reinitialized. I just didn't want to change too much of the TouchScript code locally and let you decide which route to take.

Greetings ZereZ

**Comment by valyard** [comment]
Right, this is a bug. I'll add it to the list and will fix it somehow. 
Thanks.

**Comment by valyard** [comment]
Fixed in https://github.com/TouchScript/TouchScript/releases/tag/9.0
