### ISSUE TITLE
`CustomSampler' could not be found

### ISSUE THREAD

**Issue by ayanamichaos** [TouchScript/TouchScript#252]
I imported 9.0.0 unityPackage, there are many errors in the plugins.
The error is all about `CustomSampler' could not be found.

**Comment by valyard** [comment]
Is your Unity version earlier than 5.6? CustomSampler is a 5.6 thing.

**Comment by valyard** [comment]
I added defines which disable CustomSampler code in 5.5 and earlier.
You can download code from master branch and replace it in your project.
