### ISSUE TITLE
Standard-Slider TUIO flicker

### ISSUE THREAD

**Issue by Dragonseel** [TouchScript/TouchScript#253]
When touching the Slider via TUIO, the slider will until moved jump to position 0.
This does not happen with the Standard-Input of TouchScript.

Using a Unity-Standard UI slider in Unity 2017.1.0f3 and using TouchScript with TUIO Input enabled.
I have not altered any component of TouchScript nor has the Silder any additional scripts to it.
I emulate TUIO using the reacTIVision TUIO Simulator.
I use the TouchScript version that is in the AssetStore as of the morning of 1. August 2017.

**Comment by valyard** [comment]
Fixed in 78e78c1c244fb68aad67df4d41735e76fe221778.
Can you please try current master branch?

**Comment by Dragonseel** [comment]
Tried it, and it is fixed for me! Thanks.
