### ISSUE TITLE
Only accepting every second touch

### ISSUE THREAD

**Issue by Universalerror** [TouchScript/TouchScript#255]
Hi all,
I have added the Standard Input, Fullscreen Layer and Touch manager scripts to my scene and everything is mostly in working order; objects rotate, buttons press etc. The issue is that the application only responds to every second or third touch. Have I missed anything?

Platform: Windows 10
Unity version: 5.6.2f1
Touchscript version: Latest as of 18/08/2017

**Comment by valyard** [comment]
Is the behavior the same if you build Example scenes?
Do other apps work fine?

**Comment by Universalerror** [comment]
Hi, thanks for the quick reply.
I've localised the issue to a conflicting script from another source. This issue is safe to close.
