### ISSUE TITLE
Touchscript does nt work after turning back main camera on/off

### ISSUE THREAD

**Issue by freddg** [TouchScript/TouchScript#259]
Hi,
first of all : thanks a lot for your fantastic job ! 
I hope you may help us.
I ve got unity 2017.1 + touchscript v9.
this is a bug that is very annoying for us.

you could reproduce it like that :
please open your example "Photos" (Touchscript/Examples/Photos).

you can see that your buttons are active (red/green/pink/cyan). everything is nice !
but if you turn off the "Main Camera" in the editor and turning back on : all the buttons become inactive.
it seems that you can not access any UI things...

any clues ?

thanks in advance

**Comment by valyard** [comment]
Thank you for reporting this issue. The problem was with disabling StandardLayer.
Fixed in the recent develop branch.
