### ISSUE TITLE
TouchScriptInputModule not triggering OnPointerExit from IPointerExitHandler.

### ISSUE THREAD

**Issue by falez** [TouchScript/TouchScript#264]
Unity's PointerInputModule and its variants handle this correctly. Having TouchScriptInputModule and PointerInputModule at the same time won't work either, PointerInputModule will trigger OnPointerEnter and then OnPointerExit every time the pointer position changes inside the region.

I'm not even sure if the two are supposed to be used together, seems like TouchScriptInputModule is supposed to be replacement of PointerInputModule when TouchScript is used.

**Comment by valyard** [comment]
Sorry, I missed this message. Do you still have this issue with the latest develop branch?
I've fixed a few UI related issues recently.

**Comment by adarapata** [comment]
@valyard 
Hi. I am having the same problem. Here is the sample. 
https://github.com/adarapata/touchscript-issue-example
Version has been confirmed at 2017.4.2f2. 🙏

**Comment by Jashengmato** [comment]
I am having the same problem.
Unity Version: 5.6.7f1
