### ISSUE TITLE
(Suggested solution) PointerCursor doesn't update properly prefab position in Init function using Unity 2017.2.0f3

### ISSUE THREAD

**Issue by meffe84** [TouchScript/TouchScript#266]
HI,
I've recently updated Unity to version 2017.2.0f3 and I've noticed that the MousePointers added to the scene are badly positioned (they mantain the prefab position (500, 300)) in their first frame (i.e. after the PointerCursor.Init()). When the pointer is updated in its next frames the positions return to be correct.

I've noticed it both playing the application leaving the mouse still and adding a second pointer with Alt. In both cases it's possible to see in the Scene View of Unity the rect of the pointer placed in (500, 300).

![pointerposition](https://user-images.githubusercontent.com/32843575/31618094-44cf8fca-b291-11e7-8347-a430081fe1fa.jpg)
![pointerposition2](https://user-images.githubusercontent.com/32843575/31618266-c73217ee-b291-11e7-80b7-19cf8e89e26a.jpg)

I've found a workaround for this problem that consists in delaying the call to PointerCursor.UpdatePointer(IPointer pointer) in the PointerCursor.Init() function after a frame

```c#
        public void Init(RectTransform parent, IPointer pointer)
        {
            hash = uint.MaxValue;
            group = GetComponent<CanvasGroup>();

            show();
            rect.SetParent(parent);
            rect.SetAsLastSibling();
            state = CursorState.Released;

            StartCoroutine(UpdatePointerNextFrame(pointer));
//            UpdatePointer(pointer);
        }

        private IEnumerator UpdatePointerNextFrame(IPointer pointer)
        {
            yield return null;
            UpdatePointer(pointer);
        }
```

**Comment by valyard** [comment]
Thanks. I've seen this behavior but it might be one of the UI regressions in 2017.2. I'll wait for a couple of patches and see what's going on.

**Comment by valyard** [comment]
Tried the solution you posted. The cursor "blinks" for one frame which it stays at (500, 300) before moving the frame after, which also doesn't look good )8

**Comment by valyard** [comment]
2017.2p1 fixes this.
