### ISSUE TITLE
Not able to modify StandardLayer's name 

### ISSUE THREAD

**Issue by SquareLi** [TouchScript/TouchScript#268]
Hello!

I have two standard layers in my scene, one is for 3d object, another is for UI. I did not put them in one layer because I need to identify which layer the touch hits using pointer.GerPressData(). Both layers are attached to MainCamera, so they have a same name in TouchManager. I had to modified StandardLayerEditor in order to be able to customize the name. Is it possible to include this in the official build?

Thanks,

Ang

**Comment by valyard** [comment]
Sure. How does the inspector of StandardLayer look now with your modifications?
I mean what UX you want with this feature?

**Comment by SquareLi** [comment]
Sorry for the delayed reply. Below is what i'm having:
![image](https://user-images.githubusercontent.com/1891471/32631616-bfcffd8c-c56e-11e7-97e1-156b9b0522ef.png)

So basically, i just exposed the Name field in StandardLayerEditor.cs.

**Comment by valyard** [comment]
Added in develop branch.
