### ISSUE TITLE
Touchscript breaks compatibility with Unity touch

### ISSUE THREAD

**Issue by Wolfos** [TouchScript/TouchScript#270]
We're using Touchscript in some scenes of our game, but other scenes still rely on the old touch system. If TouchScript is loaded only once, the GUI breaks everywhere unless I add a TouchScript Input Module to every scene. So, every scene has a TouchScript Input Module. However, this breaks Unity's built-in touch system. Is there any way to fix this?

Also I'm using TouchScript 8.3 because 9 is not stable on our touchscreen.

**Comment by valyard** [comment]
Could you provide an example with a couple of scenes for your case? I've never thought about this before. Also, what do you mean by TS 9 not being stable?

**Comment by Wolfos** [comment]
I 'fixed' it by converting the game to use TouchScript everywhere. Took a while but it's done.

TS 9 causes crashes when testing on hardware (Windows 10 with a custom 70" Amongo touchscreen). We tested this using the Photos sample (with the cat pictures).

**Comment by valyard** [comment]
Do you have more info on those crashes? Unity logs or crash dump?
