### ISSUE TITLE
Gesture values cannot be modified if there are two inspectors.

### ISSUE THREAD

**Issue by ganaware** [TouchScript/TouchScript#271]
Example:
1. Add a new inspector panel, and layout inspectors side by side.
2. Create an empty GameObject.
3. Add LongPressGesture to it.
4. Click "Switch to Advance" button.
5. Check "Limit Movement (cm)" and modify the value from infinity to 123.
6. The value is still infinity. I cant modify it!

TouchScript v9.0, Unity 2017.2.0p2, Windows7

**Comment by valyard** [comment]
Indeed. I guess my custom inspector is wrong. Will investigate.

**Comment by valyard** [comment]
Closing as a minor issue. Looking for the power of open source to fix this some day.
