### ISSUE TITLE
input sources only contain stand input , How do I get it to receive Tuio messages on window 10 and Unity 5.6.2

### ISSUE THREAD

**Issue by Laptter** [TouchScript/TouchScript#274]

**Comment by Laptter** [comment]
ok,i find it---

**Comment by jaxLiu1990** [comment]
how to find it ??

**Comment by valyard** [comment]
To enable TUIO you need to check TUIO checkbox in TouchScript configuration window (Window > TouchScript). This will enable TuioInput which you need to add to your scene to be able to listen to TUIO messages. After that everything should start working.

**Comment by ChinaBurn** [comment]
please tell me how to add TuioInput? i can find "TuioInput",but i don't konw how to use it
