### ISSUE TITLE
How to access the cursors screenposition

### ISSUE THREAD

**Issue by kallerosendahl** [TouchScript/TouchScript#276]
Hello, I would like to send a raycast from the screenPosition of my touchInput... Is there an easy way to get the pointers current position or do I have to edit the code and in some way via setting the rectTransform to public and acces through rect.anchoredPosition from the pointerCursor script etc. Any suggestions?

**Comment by kallerosendahl** [comment]
Maybe I should explain further... my actual problem is that I have a hexagonal map looks good. Now I want to be able to have units that can move from a node to another node. But in order to do that I need some pathfinding, and the onlypart I have left is to convert to NodeFromWorldPosition(Vector3) and since I have hexagons its quite hard to do it mathematically due to their weird geometry :)

**Comment by kallerosendahl** [comment]
So when i tap a hexagon i need it to start the pathfinding script

**Comment by valyard** [comment]
But if you tapped a tile you already know which tile was tapped. Why do you need additional raycasting? Also all TouchPointers have Position property in screen coordinates.

**Comment by kallerosendahl** [comment]
oh thx for the quick answer. 
first of all. i wanna assign like buildings and stuff on the tiles which would block and confuse what I tapped, im not very experienced with this library.

(1) how do i know which touchpointer that was active last.
i noticed that when i have pressed multiple fingers on the screen it results in multiple "inactive pointer" so which one is which?

(2)
one easy way would be to just add a tapGesture to every tile. but then the problem is the OnTap() i would like to set the Object to gameObject.. and since im dynamically creating the grid its hard to find the OnTap() function in the scripts and set it to "gameObject"

**Comment by valyard** [comment]
(1) the disabled objects are just pooled touch visualizers, you shouldn't touch them
(2) this depends on whether you want your buildings to be _individually_ tapped or not

if only tapable objects are tiles you can just add TapGesture to tiles and if tile buildings are children of the tile gameobject in hierarchy and have colliders you will get a proper tap event. if not, placing a TapGesture on the tile and objects inside of the tile, and making them "friendly" would probably work (i.e. the tile and an object will both get tap events).

**Comment by kallerosendahl** [comment]
Ok thx that cleared some things up.. still a few problems thogh but i will create a new issue since we are quite off topic
