### ISSUE TITLE
Won't play nice with TMP.

### ISSUE THREAD

**Issue by SabreRunner** [TouchScript/TouchScript#277]
I have TouchScript in the same project as TextMeshPro.
I have set up Touchscript so I could drag a background sprite around and it works fine.
But when it's active and I open a UI dialog with a TextMeshPro Input Field, I can't type in anything. It's selected when I press it and then immediately get deselected. Turning off the Touch Manager and the Standard Layer on the camera makes everything work fine. But if I start with it turned off and then turn it on later, dragging doesn't work.
Help?

**Comment by valyard** [comment]
Don't you have an EventSystem with default Unity input module in the scene? This interferes with UI.

**Comment by SabreRunner** [comment]
So, turn it off? What about axes and other input methods? I lose all that when I remove it.

**Comment by valyard** [comment]
Add TouchScript Input Module instead. It should duplicate the required functionality.

**Comment by SabreRunner** [comment]
Ok. Got it working. Thank you. I wish the documentation for proper set up was better written.

**Comment by valyard** [comment]
Good that you got it working.
One thing I wonder though — where did you go first looking for documentation?
Wasn't example scenes enough?

**Comment by SabreRunner** [comment]
No, they weren't really explained. A scene with no explanation as why certain decisions were made doesn't help me understand how the system works.
