### ISSUE TITLE
Get HitInputs

### ISSUE THREAD

**Issue by kallerosendahl** [TouchScript/TouchScript#279]
Hi again ^^

i will try to keep it short:

(1). You mentioned touchPointer, in what ways can i get the touchPointer variable.. All i can do is to create a new touchPointer which not seems right.

(2) The HitData class seems very interesting but as usual i dont understand, HOW do i get the correct value and not anything that isnt assigned ( nullreferences)

So in general my problem is that I dont want any nullrefernces for my raycasts and just get the object that was hit as easy as possible

**Comment by valyard** [comment]
Most of TouchScript functionality works through Gestures. If you attach a TapGesture to your tile you will get an event when this particular tile is tapped. In this manner you attach a gesture to every tile and your event handler code knows what particular tile is tapped.

**Comment by kallerosendahl** [comment]
xD 

> "...you will get an event when this...."

 my main problem is to find out where or how i get that event :D

**Comment by kallerosendahl** [comment]
i found out where to get it.. and it have to be on a script attached to the same object as the gesture.. and from there i do GetComponent<TapGesture>() to get it
