### ISSUE TITLE
Edit Gestures in script

### ISSUE THREAD

**Issue by kallerosendahl** [TouchScript/TouchScript#280]
Hi, If you are creating a mesh dynamically, and u do as following:

gameObjectToCreate = new GameObject();
gameObjectToCreate.AddComponent<TapGesture>();
gameObjectToCreate.GetComponent<TapGesture>().SOMETHING;  // here I want to send a Unity message to this newly created gameObject  so i set something like  ().SetUnityMessageFunction(gameObjectToCreate, functionToCall);

basically what i want is to set the target for my unityMessages to be the gameObject the tapGesture is attached to and since all is done in a generate class i cannot set the tapGestures in my inspector

**Comment by kallerosendahl** [comment]
does this work?
TapGesture().tapped += Tile.tappedTile(go);

then i only have one question and thats how to remove the function.. becuase .tapped is called when tapped only so i cant really do:
TapGesture().tapped -= Tile.tappedTile(go);

like with the OnEnable and OnDisable in the  examples :/

**Comment by valyard** [comment]
Your code is not syntactically correct, so I don't really understand what you are trying to do.
Another thing is that you should never use Unity messages api.

**Comment by kallerosendahl** [comment]
hmmm i can understand that you dont understand ^^ 
so what ur saying, is that the option in my advanced section in the inspector of a TapGesture should not be used since its slow...  what are the other alternatives if I want to for example to set some static bool to true when tapped ? and then when i press some other tile i set the true bool to false and the new tiles bool to true

**Comment by kallerosendahl** [comment]
ok I checked the examples for the hundredth time and i finally understood.. how it works logically xD
i have no problems now
