### ISSUE TITLE
(Q) multiple gestures on one object?

### ISSUE THREAD

**Issue by kallerosendahl** [TouchScript/TouchScript#281]
Hi is it possible to have for example 2 TapGestures attached to one gameobject, i kinda want to be able to both single tap and double tap on the object but then in my code it gets confusing since im doing as follows:

public TapGesture tap;
public TapGesture doubleTap;

    private void OnEnable()
    {
        if (GetComponent<TapGesture>() != null)
            tap = GetComponent<TapGesture>();
        else Debug.Log("No tapgesture attached to" + gameObject);
        tap.Tapped += tappedHandler;
    }

    private void OnDisable()
    {
        if(tap != null)
            tap.Tapped -= tappedHandler;
    }

i realise that when i want to assign my doubleTap like this: doubleTap= GetComponent<TapGesture>(); 
it should return the same as tap so that would mean that tap=doubleTap=component<TapGesture>

also i cannot add it via the inspector since the gameobjects are created via code and to assign the prefabs that are instantiated would not be the correct way any idea?

**Comment by valyard** [comment]
If you can't do this in the editor you should use GetComponents() and configure TapGestures you get separately. The configuration should be the following:
Double tap gesture — number of taps:2, time limit: 0.6
Single tap gesture — number of taps: 1, require other gesture to fail: [double tap gesture]
I am actually not sure if any example contains a demo of this setup. Will need to check this.

**Comment by kallerosendahl** [comment]
ok that should do it, smart lol didnt think of the solutation that i could configure them to be the right gestures :D but thanks
//Kalle
