### ISSUE TITLE
Application crashes on exit when using WMTouch Input

### ISSUE THREAD

**Issue by paulhoux** [TouchScript/TouchScript#3]
First of all, thank you for this great Unity library! It's a breeze to work with and well thought-out. 

We noticed that the application always crashes on exit (Alt+F4 or closing the window) when using the WMTouch Input script. This is a big problem for us, because we want to run the application unattended. Could you please look into this?

Platform: Windows 7 Ultimate
Unity: version 4.0.1f2

Kind regards.

**Comment by sloopidoopi** [comment]
Regression Bug with commits
 https://github.com/TouchScript/TouchScript/commit/56e4978cf47cec257c0d62878051569463e35e45
https://github.com/TouchScript/TouchScript/commit/ad8030423be6d9ae0d6a22ef712803a67b069491

**Comment by valyard** [comment]
@sloopidoopi: can you try if this commit works for you?
https://github.com/TouchScript/TouchScript/commit/0cc4f070fde2d148e51dca3ee9a1dcc041c740fa

**Comment by sloopidoopi** [comment]
Yes it works!
