### ISSUE TITLE
Gesture Does not Work on Windows build x86-64

### ISSUE THREAD

**Issue by Pengcheng-Wang** [TouchScript/TouchScript#329]
I build the game using Unity 2018.2.2f1 on a windows 10 machine, utilizing x86-64 setting. The tap gestures which work well in Unity editor do not work any more in the windows build. If I build a 32-bit x86 game using Unity, all tap gestures work but the game program does not recognize regular mouse input and regular touch input from Input any more. Has anyone seen similar problems?

**Comment by jonkeee** [comment]
I have the very same problem in Unity 2017.2.3p4 and Unity 20183.0f2. In Editor everything works fine.
But if i build any Win 10 player 32bit and 64 bit. 
- The Cursor Simulator second touch is not working.
- The EventSystems seems to get no events.
- No regular Mouseinput and touchinput via Input
Any fix?

**Comment by doukasd** [comment]
I had the same, touch input working in the Editor (2018.3.6) but not in the build (Windows 10).

I solved it by going to Touch Manager -> Standard Input behaviour, show advanced settings and under the Windows tab set the Windows 7 and Windows 8+ API from "Windows *" to "Unity".

**Comment by Pengcheng-Wang** [comment]
Hi, I solved my problem before, but cannot get access to the project right now. I remembered it is related to the Windows standard input API setting. I either changed it from using windows API to Unity API, or the other way, to make it both working on editor and windows build. Please refer to issue #240
