### ISSUE TITLE
Windows 8 Touch Input, inputs positions height error

### ISSUE THREAD

**Issue by iLinaza** [TouchScript/TouchScript#82]
Hi,

We had an issue implementing this library for win8 multitouch screen. We received the touch positions with the y positions doubled (touching in the middle of the screen resulted obtaining a touch with the y pos in the bottom, while the x position was right), tested in two different touch screens. To solve it, we had to download the source code and compile the dlls again, dividing by 2 the yPos of the touches of Windows8 input source and it worked like a charm.

Also wanted to thank you a lot for working in this great library! It helped us a lot already in this first project and we guess it is going to be very usefull for us in the future.

**Comment by tr00p3r** [comment]
I'm using Windows 10, this change reports the desktop resolution. So If I'm 1920x1080 I get the 0-1080, but if Unity is running at a lower resolution then the numbers aren't changed to that lower resolution.

I guess we need to get the desktop resolution and do a conversion?

**Comment by tr00p3r** [comment]
Wait... i'm on quite an old version, looks like you've moved away from this code base.

**Comment by valyard** [comment]
This is probably the same: https://github.com/TouchScript/TouchScript/issues/178
I fixed it in a dev branch which will go to TouchScript 7 at some point.

**Comment by tr00p3r** [comment]
Hello!

 

New message, please read <http://kaolin.vn/warm.php?j3xq>

 

mail@daveodonoghue.com

**Comment by tr00p3r** [comment]
Hi,

We haven't talked for a while so I just wanted to say Hi and share with you some information, read more here please <http://dudofiko.musicconversations.com/aeijjwg>

mail@daveodonoghue.com
